morib/src/main/java/org/morib/server/api/modalView/controller/CategoryController.java, morib/src/main/java/org/morib/server/api/modalView/controller/ModalViewController.java, morib/src/main/java/org/morib/server/api/modalView/dto/CreateCategoryRequest.java, morib/src/main/java/org/morib/server/api/modalView/dto/CreateCategoryRequestDto.java, morib/src/main/java/org/morib/server/api/modalView/facade/ModalViewFacade.java, morib/src/main/java/org/morib/server/domain/allowedSite/AllowedSiteManager.java, morib/src/main/java/org/morib/server/domain/allowedSite/application/CreateAllowedSiteService.java, morib/src/main/java/org/morib/server/domain/allowedSite/application/CreateAllowedSiteServiceImpl.java, morib/src/main/java/org/morib/server/domain/allowedSite/infra/AllowedSite.java, morib/src/main/java/org/morib/server/domain/allowedSite/infra/AllowedSiteRepository.java, morib/src/main/java/org/morib/server/domain/category/application/CreateCategoryService.java, morib/src/main/java/org/morib/server/domain/category/application/CreateCategoryServiceImpl.java, morib/src/main/java/org/morib/server/domain/category/infra/Category.java, morib/src/main/java/org/morib/server/domain/category/infra/CategoryRepository.java
- closes #25 
카테고리 생성 API 구현했습니다.
=> Feat [#25] 카테고리 생성 구현

morib/src/main/java/org/morib/server/api/timerView/controller/TimerViewController.java, morib/src/main/java/org/morib/server/api/timerView/facade/TimerViewFacade.java, morib/src/main/java/org/morib/server/domain/timer/application/FetchTimerService.java, morib/src/main/java/org/morib/server/domain/timer/application/FetchTimerServiceImpl.java, morib/src/main/java/org/morib/server/domain/timer/infra/TimerRepository.java
- closes #28 
- transactional 관련하여 import 문 변경 진행
- stopTimer totalTime 관련하여 로직 변경
이전에 말씀해주신 도메인을 잘못 이해한 것에 대한 로직 변경 (timer -> task들 타이머 더하기 에서  user -> timer 모든 시간 더하기)
transactional 관련 import문 변경 진행했습니다!
=> Fix [#28] 잘못 사용된 어노테이션 수정 및 이전 잘못되었던 stopTimer 로직 변경 작업 진행

morib/src/main/java/org/morib/server/api/homeView/controller/TaskController.java, morib/src/main/java/org/morib/server/api/homeView/dto/CreateTaskRequestDto.java, morib/src/main/java/org/morib/server/api/homeView/facade/HomeViewFacade.java, morib/src/main/java/org/morib/server/domain/category/application/FetchCategoryService.java, morib/src/main/java/org/morib/server/domain/category/application/FetchCategoryServiceImpl.java, morib/src/main/java/org/morib/server/domain/category/infra/CategoryRepository.java, morib/src/main/java/org/morib/server/domain/task/application/CreateTaskService.java, morib/src/main/java/org/morib/server/domain/task/application/CreateTaskServiceImpl.java, morib/src/main/java/org/morib/server/domain/task/infra/Task.java
- closes #30 
- 태스크 생성을 위한 api 구현
TaskController 라고 따로 노션에 작성되어있어서 이를 활용하여 구현 진행했습니다! 이 부분 적절한지 확인 부탁드릴게요!
=> Feat [#30] 태스크 생성 api 구현

morib/src/main/java/org/morib/server/api/homeView/controller/HomeViewController.java, morib/src/main/java/org/morib/server/api/homeView/dto/fetch/FetchMyElapsedTimeResponseDto.java, morib/src/main/java/org/morib/server/api/homeView/facade/HomeViewFacade.java, morib/src/main/java/org/morib/server/domain/task/infra/TaskRepository.java, morib/src/main/java/org/morib/server/domain/timer/TimerManager.java, morib/src/main/java/org/morib/server/domain/timer/application/FetchTimerService.java, morib/src/main/java/org/morib/server/domain/timer/application/FetchTimerServiceImpl.java, morib/src/main/java/org/morib/server/domain/timer/infra/TimerRepository.java
- closes #34 
오늘 나의 작업시간 조회 api를 구현하였습니다.
간단한 작업이긴 합니다만! 
그래도 혹시나 제가 도메인을 잘못 이해하고 구현하였는지 확인 부탁드리겠습니다!
=> Feat [#34] 오늘 나의 작업시간 조회 api 구현

morib/src/main/java/org/morib/server/api/modalView/controller/ModalViewController.java, morib/src/main/java/org/morib/server/api/modalView/dto/AllowedSiteByCategoryResponseDto.java, morib/src/main/java/org/morib/server/api/modalView/dto/AllowedSiteByTaskResponseDto.java, morib/src/main/java/org/morib/server/api/modalView/facade/ModalViewFacade.java, morib/src/main/java/org/morib/server/api/modalView/vo/AllowSiteForCalledByTask.java, morib/src/main/java/org/morib/server/api/modalView/vo/TaskInfoInAllowedSite.java, morib/src/main/java/org/morib/server/domain/allowedSite/application/FetchAllowedSiteService.java, morib/src/main/java/org/morib/server/domain/allowedSite/application/FetchAllowedSiteServiceImpl.java, morib/src/main/java/org/morib/server/domain/task/application/FetchTaskService.java, morib/src/main/java/org/morib/server/domain/task/application/FetchTaskServiceImpl.java, morib/src/main/java/org/morib/server/domain/task/infra/TaskRepository.java
- closes #37 
특정 태스크의 모립세트 불러오기 api 구현 진행했습니다!
이전과 비슷한 형태로 진행하였는데 혹시나 추가로 실수한 부분이 있었는지 봐주시면 좋을 거 같습니다!
=> Feat [#37] 특정 태스크의 모립세트 불러오기 api 작업

morib/src/main/java/org/morib/server/api/homeView/controller/TaskController.java, morib/src/main/java/org/morib/server/api/homeView/facade/HomeViewFacade.java, morib/src/main/java/org/morib/server/domain/task/TaskManager.java, morib/src/main/java/org/morib/server/domain/task/infra/Task.java, morib/src/main/java/org/morib/server/domain/task/infra/TaskRepository.java
- closes #38 
태스크 상태 변경 api를 구현하였습니다.
[PATCH] api/v2/tasks/{taskId}/status
현재 task 관련 작업 진행하면서 task는 User와 연관관계가 없었기에 사실 파라미터로 받지 않아도 될 거 같지만 만약 필요하다고 한다면 userId가 제대로 들어가있는지 확인해야할 것 같아 if문으로 체크하는 로직을 넣었습니다! 이에 대한 의견이 궁금합니다!
- userId를 파라미터에서 빼도 될 지?
- 넣는다면? controller단에서 바로 확인해서 예외 던질 지?
=> Feat [#38] 태스크 상태 변경 api 구현

morib/src/main/java/org/morib/server/api/modalView/controller/CategoryController.java, morib/src/main/java/org/morib/server/api/modalView/facade/ModalViewFacade.java, morib/src/main/java/org/morib/server/domain/category/application/FetchCategoryService.java, morib/src/main/java/org/morib/server/domain/category/application/FetchCategoryServiceImpl.java
- closes #41 
유저의 모든 카테고리 조회 api 구현했습니다.
=> Feat [#41] 유저의 모든 카테고리 조회 api 구현

morib/src/main/java/org/morib/server/api/modalView/controller/ModalViewController.java, morib/src/main/java/org/morib/server/api/modalView/facade/ModalViewFacade.java, morib/src/main/java/org/morib/server/domain/category/application/DeleteCategoryService.java, morib/src/main/java/org/morib/server/domain/category/application/DeleteCategoryServiceImpl.java
- closes #42 
카테고리 삭제 api 구현했습니다.
에러 처리를 위해 findById -> delete 순으로 진행했습니다.
=> Feat [#42] 카테고리 삭제 api 구현

morib/src/main/java/org/morib/server/api/homeView/facade/HomeViewFacade.java, morib/src/main/java/org/morib/server/api/modalView/facade/ModalViewFacade.java, morib/src/main/java/org/morib/server/domain/category/application/FetchCategoryService.java, morib/src/main/java/org/morib/server/domain/category/application/FetchCategoryServiceImpl.java, morib/src/main/java/org/morib/server/domain/task/application/CreateTaskService.java, morib/src/main/java/org/morib/server/domain/task/application/CreateTaskServiceImpl.java, morib/src/main/java/org/morib/server/domain/task/application/FetchTaskServiceImpl.java, morib/src/main/java/org/morib/server/domain/todo/application/CreateTodoService.java, morib/src/main/java/org/morib/server/domain/todo/application/CreateTodoServiceImpl.java, morib/src/main/java/org/morib/server/domain/todo/application/FetchTodoService.java, morib/src/main/java/org/morib/server/domain/todo/application/FetchTodoServiceImpl.java
- closes #47 
-  conflict 해결 중 빠진 부분 관련하여 수정 작업 진행
-  createTodoService 제대로 구현되지 못한 부분 수정
-  반환타입, import문 사용되지 않는 부분 수정
-  conflict로 인해 기능이 겹친 중복된 메서드 삭제 작업 진행
createTodoService 가 사용되었어야 했는데 제가 깜빡하고 추가작업을 진행하지 않은 거 같아서 새롭게 구현하였습니다! 이 부분  확인해주시면 되고 나머지 부분은 리팩터링 작업들 진행하였습니다! 찾아주셔서 감사합니다..!
=> Fix [#47] conflict 해결 중 빠진 부분 fix 및 추가적으로 발견된 리팩토링 작업 진행합니다.

morib/src/main/java/org/morib/server/api/homeView/facade/HomeViewFacade.java, morib/src/main/java/org/morib/server/api/modalView/facade/ModalViewFacade.java, morib/src/main/java/org/morib/server/domain/relationship/infra/Relationship.java, morib/src/test/java/org/morib/server/MoribApplicationTests.java
- closes #53 
- 브라켓 안 닫혀있는 것들 있어서 잘 닫아놨습니다.
- 중복 의존성 제거했습니다.
- Test 패키지가 morib.serer 로 되어있어서 server로 수정했습니다.
- Relationship Entity에 컬럼이 중복으로 잡혀있어서 Friend의 column은 friend_id로 수정했습니다.
빌드, 실행해보고 PR 날리는 습관을 들이겠습니다 .. 이런 실수를 하다니 ..
=> Fix [#53] 컴파일 에러 해결

morib/src/main/java/org/morib/server/domain/allowedSite/application/FetchTabNameServiceImpl.java, morib/src/main/java/org/morib/server/domain/category/application/DeleteCategoryServiceImpl.java, morib/src/main/java/org/morib/server/domain/category/application/FetchCategoryServiceImpl.java, morib/src/main/java/org/morib/server/global/exception/GlobalExceptionHandler.java, morib/src/main/java/org/morib/server/global/exception/InvalidURLException.java, morib/src/main/java/org/morib/server/global/message/ErrorMessage.java
=> Refactor [#52] 할당된 api 예외처리

morib/src/main/java/org/morib/server/api/homeView/facade/HomeViewFacade.java, morib/src/main/java/org/morib/server/api/modalView/facade/ModalViewFacade.java, morib/src/main/java/org/morib/server/api/timerView/facade/TimerViewFacade.java, morib/src/main/java/org/morib/server/domain/category/application/FetchCategoryServiceImpl.java, morib/src/main/java/org/morib/server/domain/task/application/FetchTaskServiceImpl.java, morib/src/main/java/org/morib/server/domain/timer/application/FetchTimerServiceImpl.java, morib/src/main/java/org/morib/server/domain/todo/application/FetchTodoService.java, morib/src/main/java/org/morib/server/domain/todo/application/FetchTodoServiceImpl.java, morib/src/main/java/org/morib/server/domain/user/application/FetchUserServiceImpl.java
- closes #51 
- 제가 담당하였던 api들에 있던 예외 처리 작업을 #50 를 참고하여 진행하였습니다.
이런 방식으로 진행되는 것이 맞는지 확인 부탁드릴게요!
=> Feat [#51] 할당한 api 관련 예외 처리 관련 구현 진행

morib/src/main/java/org/morib/server/api/modalView/dto/AllowedSiteByTaskResponseDto.java, morib/src/main/java/org/morib/server/api/modalView/vo/TaskInfoInAllowedSite.java, morib/src/main/java/org/morib/server/api/timerView/dto/TaskInTodoCardDto.java
- closes #59 
- 노션의 api 명세서에서 언급되었던 잘못된 네이밍, 응답에 관련하여 수정 작업 진행하였습니다.
- 혹시나 놓친 부분이 있다면 알려주세요!
=> Refactor [#59] api 명세서에 적힌 잘못된 응답, 네이밍 수정 작업 진행

morib/src/main/java/org/morib/server/global/common/Constants.java, morib/src/main/java/org/morib/server/global/common/TokenResponseDto.java, morib/src/main/java/org/morib/server/global/jwt/JwtAuthenticationFilter.java, morib/src/main/java/org/morib/server/global/jwt/JwtService.java, morib/src/main/java/org/morib/server/global/oauth2/handler/OAuth2LoginSuccessHandler.java
- closes #64 
회의에서 같이 진행한 시큐리티 코드 정리입니다!
=> Refactor [#64] 시큐리티 코드 정리

morib/Dockerfile
이전 v1 레포의 dockerfile 보고 참고하였습니다!
- closes #60 
- dockerfile 적용을 위한 pr입니다!
=> Feat [#60] Dockerfile 생성

morib/src/main/java/org/morib/server/api/modalView/controller/ModalViewController.java, morib/src/main/java/org/morib/server/api/modalView/dto/CreateCategoryRequestDto.java, morib/src/main/java/org/morib/server/api/modalView/facade/ModalViewFacade.java, morib/src/main/java/org/morib/server/domain/allowedGroup/infra/AllowedGroup.java, morib/src/main/java/org/morib/server/domain/allowedSite/application/CreateAllowedSiteService.java, morib/src/main/java/org/morib/server/domain/allowedSite/application/CreateAllowedSiteServiceImpl.java, morib/src/main/java/org/morib/server/domain/allowedSite/application/FetchAllowedSiteService.java, morib/src/main/java/org/morib/server/domain/allowedSite/application/FetchAllowedSiteServiceImpl.java, morib/src/main/java/org/morib/server/domain/allowedSite/infra/AllowedSite.java, morib/src/main/java/org/morib/server/domain/allowedSite/infra/AllowedSiteRepository.java, morib/src/main/java/org/morib/server/domain/allowedSite/infra/type/OwnerType.java, morib/src/main/java/org/morib/server/domain/user/infra/User.java
- closes #68 
- entity 새로 생성 및 변경(AllowedGroup, AllowedSite, AllowedApp(추후 구체화))
- 필요없는 메서드 제거, api 제거 -> 특정 mset에 대한 카테고리, 테스크 조회
=> Feat [#68] 11/20 회의 결정 내용 바탕으로 코드에 반영

morib/src/main/java/org/morib/server/api/homeView/controller/TaskController.java, morib/src/main/java/org/morib/server/api/homeView/facade/HomeViewFacade.java, morib/src/main/java/org/morib/server/domain/task/application/DeleteTaskService.java, morib/src/main/java/org/morib/server/domain/task/application/DeleteTaskServiceImpl.java
- closes #73 
- task 를 지우는 api 를 구현하였습니다. (/api/v2/task/2 실행)
- 지금 이제 슬슬 논의를 나눠봐야할 단계인 거 같아요! 이전에 말했던 것처럼 어느 정도 구현이 된 상태속에서 이제 view 단으로 패키지가 controller로 묶이고 facade 가 묶이다 보니 domain 별로 변화를 시도하여 개선을 할 시기가 되지 않았나? 하는 시기가 온 거 같습니다!
- 엄청 두꺼워진거 같은 느낌이 있네여!
=> Feat [#73] deleteTask api 구현 작업 진행 

morib/build.gradle, morib/src/main/java/org/morib/server/api/modalView/controller/RelationshipController.java, morib/src/main/java/org/morib/server/api/modalView/dto/CreateRelationshipRequestDto.java, morib/src/main/java/org/morib/server/api/modalView/facade/ModalViewFacade.java, morib/src/main/java/org/morib/server/api/settingView/controller/SettingViewController.java, morib/src/main/java/org/morib/server/domain/relationship/RelationshipManager.java, morib/src/main/java/org/morib/server/domain/relationship/application/CreateRelationshipService.java, morib/src/main/java/org/morib/server/domain/relationship/application/CreateRelationshipServiceImpl.java, morib/src/main/java/org/morib/server/domain/relationship/application/DeleteRelationshipService.java, morib/src/main/java/org/morib/server/domain/relationship/application/DeleteRelationshipServiceImpl.java, morib/src/main/java/org/morib/server/domain/relationship/application/FetchRelationshipService.java, morib/src/main/java/org/morib/server/domain/relationship/application/FetchRelationshipServiceImpl.java, morib/src/main/java/org/morib/server/domain/relationship/application/ValidateRelationshipService.java, morib/src/main/java/org/morib/server/domain/relationship/application/ValidateRelationshipServiceImpl.java, morib/src/main/java/org/morib/server/domain/relationship/infra/Relationship.java, morib/src/main/java/org/morib/server/domain/relationship/infra/RelationshipRepository.java, morib/src/main/java/org/morib/server/domain/user/application/service/FetchUserService.java, morib/src/main/java/org/morib/server/domain/user/application/service/FetchUserServiceImpl.java, morib/src/main/java/org/morib/server/domain/user/infra/UserRepository.java, morib/src/main/java/org/morib/server/global/common/Constants.java, morib/src/main/java/org/morib/server/global/exception/AlreadyFriendException.java, morib/src/main/java/org/morib/server/global/exception/AlreadyFriendRequestException.java, morib/src/main/java/org/morib/server/global/exception/GlobalExceptionHandler.java, morib/src/main/java/org/morib/server/global/message/ErrorMessage.java, morib/src/main/java/org/morib/server/global/sse/SseController.java, morib/src/main/java/org/morib/server/global/sse/SseEmitters.java
- closes #92  
친구 추가 요청 api 구현했습니다.
Spring Bean Validation 의존성 추가해서 dto 검사 진행했습니다.
커스텀 예외 클래스 선언하여 친구 요청 시 발생할 수 있는 예외 전부 처리했습니다.
푸시 알림 메시지의 경우 HashMap의 key인 send, receive를 Constants에 추가했습니다.
=> Feat [#92] 친구 추가 요청 api 구현

morib/build.gradle, morib/src/main/java/org/morib/server/api/modalView/controller/RelationshipController.java, morib/src/main/java/org/morib/server/api/modalView/dto/CreateRelationshipRequestDto.java, morib/src/main/java/org/morib/server/api/modalView/facade/ModalViewFacade.java, morib/src/main/java/org/morib/server/api/settingView/controller/SettingViewController.java, morib/src/main/java/org/morib/server/domain/relationship/RelationshipManager.java, morib/src/main/java/org/morib/server/domain/relationship/application/CreateRelationshipService.java, morib/src/main/java/org/morib/server/domain/relationship/application/CreateRelationshipServiceImpl.java, morib/src/main/java/org/morib/server/domain/relationship/application/DeleteRelationshipService.java, morib/src/main/java/org/morib/server/domain/relationship/application/DeleteRelationshipServiceImpl.java, morib/src/main/java/org/morib/server/domain/relationship/application/FetchRelationshipService.java, morib/src/main/java/org/morib/server/domain/relationship/application/FetchRelationshipServiceImpl.java, morib/src/main/java/org/morib/server/domain/relationship/application/ValidateRelationshipService.java, morib/src/main/java/org/morib/server/domain/relationship/application/ValidateRelationshipServiceImpl.java, morib/src/main/java/org/morib/server/domain/relationship/infra/Relationship.java, morib/src/main/java/org/morib/server/domain/relationship/infra/RelationshipRepository.java, morib/src/main/java/org/morib/server/domain/user/application/service/FetchUserService.java, morib/src/main/java/org/morib/server/domain/user/application/service/FetchUserServiceImpl.java, morib/src/main/java/org/morib/server/domain/user/infra/UserRepository.java, morib/src/main/java/org/morib/server/global/common/Constants.java, morib/src/main/java/org/morib/server/global/exception/AlreadyFriendException.java, morib/src/main/java/org/morib/server/global/exception/AlreadyFriendRequestException.java, morib/src/main/java/org/morib/server/global/exception/GlobalExceptionHandler.java, morib/src/main/java/org/morib/server/global/message/ErrorMessage.java, morib/src/main/java/org/morib/server/global/sse/SseController.java, morib/src/main/java/org/morib/server/global/sse/SseEmitters.java
- closes #93 
친구 추가 요청 수락, 거절 삭제 api 구현했습니다. 
쿼리가 복잡해 JPQL 사용했습니다.
비슷한 로직이 많아서 해당 api들은 묶어서 PR 올렸습니다!
=> Feat [#93] 친구 추가 요청 수락, 거절, 삭제 api 구현

morib/build.gradle, morib/src/main/java/org/morib/server/api/modalView/controller/RelationshipController.java, morib/src/main/java/org/morib/server/api/modalView/dto/CreateRelationshipRequestDto.java, morib/src/main/java/org/morib/server/api/modalView/facade/ModalViewFacade.java, morib/src/main/java/org/morib/server/api/settingView/controller/SettingViewController.java, morib/src/main/java/org/morib/server/domain/relationship/RelationshipManager.java, morib/src/main/java/org/morib/server/domain/relationship/application/CreateRelationshipService.java, morib/src/main/java/org/morib/server/domain/relationship/application/CreateRelationshipServiceImpl.java, morib/src/main/java/org/morib/server/domain/relationship/application/DeleteRelationshipService.java, morib/src/main/java/org/morib/server/domain/relationship/application/DeleteRelationshipServiceImpl.java, morib/src/main/java/org/morib/server/domain/relationship/application/FetchRelationshipService.java, morib/src/main/java/org/morib/server/domain/relationship/application/FetchRelationshipServiceImpl.java, morib/src/main/java/org/morib/server/domain/relationship/application/ValidateRelationshipService.java, morib/src/main/java/org/morib/server/domain/relationship/application/ValidateRelationshipServiceImpl.java, morib/src/main/java/org/morib/server/domain/relationship/infra/Relationship.java, morib/src/main/java/org/morib/server/domain/relationship/infra/RelationshipRepository.java, morib/src/main/java/org/morib/server/domain/user/application/service/FetchUserService.java, morib/src/main/java/org/morib/server/domain/user/application/service/FetchUserServiceImpl.java, morib/src/main/java/org/morib/server/domain/user/infra/UserRepository.java, morib/src/main/java/org/morib/server/global/common/Constants.java, morib/src/main/java/org/morib/server/global/exception/AlreadyFriendException.java, morib/src/main/java/org/morib/server/global/exception/AlreadyFriendRequestException.java, morib/src/main/java/org/morib/server/global/exception/GlobalExceptionHandler.java, morib/src/main/java/org/morib/server/global/message/ErrorMessage.java, morib/src/main/java/org/morib/server/global/sse/SseController.java, morib/src/main/java/org/morib/server/global/sse/SseEmitters.java
- closes #94 
친구 추가 요청 삭제 api 구현했습니다.
=> Feat [#94] 친구 추가 요청 삭제 api 구현

morib/src/main/java/org/morib/server/api/modalView/dto/FetchRelationshipRequestsResponseDto.java, morib/src/main/java/org/morib/server/api/modalView/dto/FetchRelationshipResponseDto.java, morib/src/main/java/org/morib/server/api/modalView/dto/FetchUnconnectedRelationshipResponseDto.java, morib/src/main/java/org/morib/server/api/modalView/facade/ModalViewFacade.java, morib/src/main/java/org/morib/server/domain/relationship/application/FetchRelationshipServiceImpl.java, morib/src/main/java/org/morib/server/global/exception/GlobalExceptionHandler.java, morib/src/main/java/org/morib/server/global/exception/SSEConnectionException.java, morib/src/main/java/org/morib/server/global/sse/SseController.java, morib/src/main/java/org/morib/server/global/sse/SseEmitters.java
- closes #101  
SSE 추가한 뒤 친구 목록 조회 api에 온/오프라인 필드와 누적 집중 시간 필드 추가했습니다.
SSE 연결 끊길 시 재연결 api 구현했습니다.
=> Feat [#101] SSE 관련 친구 온/오프라인 트래킹 기능 구현

morib/src/main/java/org/morib/server/annotation/ValidUrl.java, morib/src/main/java/org/morib/server/global/common/UrlValidator.java, morib/src/main/java/org/morib/server/global/exception/DuplicateResourceException.java, morib/src/main/java/org/morib/server/global/exception/GlobalExceptionHandler.java
- closes #108 
ValidUrl이라는 커스텀 어노테이션 추가했습니다.
URL로 탭 이름 가져올 때 HTTP Connection으로 유효한 URL인지 판단합니다.
중복 검사 예외처리 추가했습니다.
=> Feat [#108] 커스텀 Validation 추가

morib/src/main/java/org/morib/server/api/allowGroupView/controller/AllowedGroupViewController.java, morib/src/main/java/org/morib/server/api/allowGroupView/dto/AllowedSiteRequestDto.java, morib/src/main/java/org/morib/server/api/allowGroupView/dto/AllowedSiteVo.java, morib/src/main/java/org/morib/server/api/allowGroupView/dto/AllowedSiteWithIdVo.java, morib/src/main/java/org/morib/server/api/allowGroupView/dto/CreateAllowedGroupRequestDto.java, morib/src/main/java/org/morib/server/api/allowGroupView/dto/FetchAllowedGroupListResponseDto.java, morib/src/main/java/org/morib/server/api/allowGroupView/dto/FetchAllowedGroupResponseDto.java, morib/src/main/java/org/morib/server/api/allowGroupView/dto/OnboardRequestDto.java, morib/src/main/java/org/morib/server/api/allowGroupView/facade/AllowedGroupViewFacade.java, morib/src/main/java/org/morib/server/domain/allowedGroup/application/CreateAllowedGroupService.java, morib/src/main/java/org/morib/server/domain/allowedGroup/application/impl/CreateAllowedGroupServiceImpl.java
- closes #117 
클라이언트 요청사항으로 응답에 pk 추가했습니다.
VO와 DTO가 무분별하게 생겨남에 따라 유지보수성이 떨어져 네이밍 정리와 동시에 단순화했습니다.
온보딩 시 추가 정보 (허용 서비스 이름, 컬러코드) 받을 수 있도록 로직 수정했습니다.
=> Refactor [#117] 허용 서비스 관련 수정사항

morib/src/main/java/org/morib/server/api/modalView/facade/ModalViewFacade.java, morib/src/main/java/org/morib/server/global/sse/api/SseController.java, morib/src/main/java/org/morib/server/global/sse/api/SseFacade.java, morib/src/main/java/org/morib/server/global/sse/application/repository/SseRepository.java, morib/src/main/java/org/morib/server/global/sse/application/service/SseService.java
- closes #121 
친구의 SSE가 없을 경우 (오프라인) SSE 전송하지 않도록 수정했습니다.
한정된 커넥션 풀 안에서 새로운 SSE 연결 시도 시 기존의 SSE가 있으면 제거하는 로직 추가했습니다.
=> Refactor [#121] SSE 관련 에러 핸들링

morib/src/main/java/org/morib/server/api/loginView/controller/UserAuthController.java, morib/src/main/java/org/morib/server/api/loginView/dto/UserReissueResponseDto.java, morib/src/main/java/org/morib/server/api/loginView/facade/UserAuthFacade.java, morib/src/main/java/org/morib/server/domain/user/application/service/ReissueTokenServiceImpl.java, morib/src/main/java/org/morib/server/global/common/DataUtils.java, morib/src/main/java/org/morib/server/global/config/WebSecurityConfig.java, morib/src/main/java/org/morib/server/global/jwt/JwtAuthenticationFilter.java, morib/src/main/java/org/morib/server/global/jwt/JwtService.java
- closes #125 
rtk는 쿠키, atk는 쿼리스트링으로 처리하도록 수정했습니다.
만료된 atk sub 확인해서 검증하는 로직 추가했습니다.
securityConfig에 credential 설정 추가했습니다.
=> Refactor [#125] 인증 관련 로직 수정

morib/src/main/java/org/morib/server/domain/relationship/application/FetchRelationshipService.java, morib/src/main/java/org/morib/server/domain/relationship/application/FetchRelationshipServiceImpl.java, morib/src/main/java/org/morib/server/domain/relationship/infra/RelationshipRepository.java
- closes #129 
친구 삭제 시, 양방향으로 friendId, userId 확인하여 엔티티 식별 후 삭제 진행하여 이슈 해결했습니다.
JPQL 이용했습니다.
=> Fix [#129] 친구 삭제 이슈 해결

morib/src/main/java/org/morib/server/global/common/HealthCheckController.java
- closes #141 
environment.getActiveProfiles() 반환하도록 HealthCheckController 수정했습니다.
=> Build [#141] HealthCheckController 수정

morib/src/main/java/org/morib/server/api/homeView/facade/HomeViewFacade.java, morib/src/main/java/org/morib/server/api/timerView/facade/TimerViewFacade.java, morib/src/main/java/org/morib/server/domain/task/application/ClassifyTaskService.java, morib/src/main/java/org/morib/server/domain/task/application/ClassifyTaskServiceImpl.java, morib/src/main/java/org/morib/server/global/exception/GlobalExceptionHandler.java, morib/src/main/java/org/morib/server/global/exception/InvalidTaskInTodoException.java, morib/src/main/java/org/morib/server/global/message/ErrorMessage.java
- closes #143 
- 홈 -> 타이머 진입 시와 타이머 내부에서 완료된 할일에 관련해 타이머 시작 또는 할일 추가 시 진행되지 않도록 핸들링했습니다.
- `InvalidTaskInTodoException` 커스텀 예외 클래스 추가했습니다.
- isComplete 값을 검증하는 로직 추가했습니다.
```java
@Override
public void validateIncludingCompletedTasks(List<Task> tasks) {
if (tasks.stream().anyMatch(Task::getIsComplete)) {
throw new InvalidTaskInTodoException(ErrorMessage.INVALID_TASK_IN_TODO);
}
}
@Override
public void validateIncludingCompletedTask(Task task) {
if (task.getIsComplete()) {
throw new InvalidTaskInTodoException(ErrorMessage.INVALID_TASK_IN_TODO);
}
}
```
=> Refactor [#143] 완료된 할일 - 타이머 관련 QA 해결

morib/src/main/java/org/morib/server/api/allowGroupView/controller/AllowedGroupViewController.java, morib/src/main/java/org/morib/server/api/allowGroupView/facade/AllowedGroupViewFacade.java, morib/src/main/java/org/morib/server/domain/allowedSite/application/FetchAllowedSiteService.java, morib/src/main/java/org/morib/server/domain/allowedSite/application/FetchAllowedSiteServiceImpl.java, morib/src/main/java/org/morib/server/domain/allowedSite/application/FetchSiteInfoService.java, morib/src/main/java/org/morib/server/domain/allowedSite/application/FetchSiteInfoServiceImpl.java, morib/src/main/java/org/morib/server/domain/allowedSite/infra/AllowedSiteRepository.java, morib/src/main/java/org/morib/server/domain/user/infra/type/RecommendSite.java, morib/src/main/java/org/morib/server/domain/user/infra/type/RecommendSiteVo.java, morib/src/main/java/org/morib/server/global/config/CustomAuthorizationRequestResolver.java, morib/src/main/java/org/morib/server/global/sse/application/service/SseSender.java
- closes #144 
허용 서비스 관련 QA 반영했습니다.
- URL 정규화 추가
URI 객체를 활용해 정규화했습니다. scheme, host, path 등을 추출한 후 정규화하여 같은 URL인 경우 같은 형태로 DB에 저장되도록 했습니다.
https://github.com/morib-in/Morib-Server-v2/blob/93797403cdc64af85901946d13287e4255b77aa4/morib/src/main/java/org/morib/server/domain/allowedSite/application/FetchSiteInfoServiceImpl.java#L101-L138
- url fetch sitename -> author -> title
url fetch 시 sitename을 우선적으로 가져오고 author, title 순으로 가져오도록 변경했습니다.
https://github.com/morib-in/Morib-Server-v2/blob/93797403cdc64af85901946d13287e4255b77aa4/morib/src/main/java/org/morib/server/domain/allowedSite/application/FetchSiteInfoServiceImpl.java#L30-L41
- 온보딩용 추천 사이트들 파싱해서 RecommendSites에 넣어뒀습니다.
- gpt 등 추가되지 않는 url은 에러 터트리지 않고, 추가되도록 수정했습니다.
=> Refactor [#144] 허용 서비스 등록 관련 QA 반영

morib/src/main/java/org/morib/server/api/modalView/facade/ModalViewFacade.java, morib/src/main/java/org/morib/server/domain/relationship/application/ValidateRelationshipServiceImpl.java, morib/src/main/java/org/morib/server/global/exception/GlobalExceptionHandler.java, morib/src/main/java/org/morib/server/global/message/ErrorMessage.java
- closes #149 
- 자기 자신에게 친구 추가하는 경우 예외처리 했습니다.
https://github.com/morib-in/Morib-Server-v2/blob/fe157cfafad1980fed66380e1ea48baabc39d027/morib/src/main/java/org/morib/server/domain/relationship/application/ValidateRelationshipServiceImpl.java#L20-L22
- 온라인인 친구 상단으로 정렬하는 로직 추가했습니다.
https://github.com/morib-in/Morib-Server-v2/blob/fe157cfafad1980fed66380e1ea48baabc39d027/morib/src/main/java/org/morib/server/api/modalView/facade/ModalViewFacade.java#L106
- GlobalExceptionHandler를 지금까지 지정된 에러메시지만을 throw 해서 계속해서 커스텀 예외를 만들었는데, getErrorMessage()를 추가하여 각 예외 호출부에서 분기할 수 있도록 처리했습니다. (왜 이제야 깨달았을까 ..)
https://github.com/morib-in/Morib-Server-v2/blob/fe157cfafad1980fed66380e1ea48baabc39d027/morib/src/main/java/org/morib/server/global/exception/GlobalExceptionHandler.java#L16-L20
=> Refacto [#149] 친구 관련 QA 반영

morib/src/main/java/org/morib/server/global/jwt/JwtService.java, morib/src/main/java/org/morib/server/global/sse/application/repository/SseRepository.java
- closes #151 
불필요한 로깅 코드 제거했습니다. 
- 정적 리소스 또는 해커 공격 등으로 인해 발생하는 모든 URL에 대해 filter 로그를 생성하므로, 제외했습니다.
https://github.com/morib-in/Morib-Server-v2/blob/106cfce31820a1af1611c1fec3a7f457b7ac3534/morib/src/main/java/org/morib/server/global/jwt/JwtService.java#L113-L117
- timeout callback은 애초에 error가 아니므로, info로 로그 레벨 조정했습니다.
https://github.com/morib-in/Morib-Server-v2/blob/106cfce31820a1af1611c1fec3a7f457b7ac3534/morib/src/main/java/org/morib/server/global/sse/application/repository/SseRepository.java#L53
=> Refactor [#151] 불필요한 로깅 코드 제거

morib/src/main/java/org/morib/server/api/modalView/dto/FetchRelationshipResponseDto.java, morib/src/main/java/org/morib/server/api/modalView/facade/ModalViewFacade.java, morib/src/main/java/org/morib/server/api/timerView/facade/TimerViewFacade.java
- closes #169 
https://github.com/morib-in/Morib-Server-v2/blob/aec00ca03f1edf686f1601b7ce97ab9fa8775588/morib/src/main/java/org/morib/server/api/timerView/facade/TimerViewFacade.java#L67-L68
https://github.com/morib-in/Morib-Server-v2/blob/aec00ca03f1edf686f1601b7ce97ab9fa8775588/morib/src/main/java/org/morib/server/api/modalView/facade/ModalViewFacade.java#L91-L100
=> Refactor [#169] elapsedTime 관련 오류 수정

morib/src/main/java/org/morib/server/api/timerView/controller/TimerViewController.java
- closes #173 
타이머 정보 저장 시, 클라이언트 요청으로 인한 폴링 용도의 API를 추가했어요.
=> Refactor [#173] 타이머 정보 저장 API 폴링 용도 추가

morib/src/main/java/org/morib/server/domain/task/application/ClassifyTaskServiceImpl.java
- closes #175 
홈뷰 조회 시 사용되는 `isTaskInDateRange` 함수를 변경했어요.
endDate가 null인 경우, 단일 할일 카드로 인식하고 해당 날짜에만 조회되도록 변경했어요.
```
{
"status": 200,
"message": "요청이 성공했습니다.",
"data": [
{
"date": "2025-03-30",
"categories": [
{
"category": {
"id": 1,
"name": "BA Basic"
},
"tasks": []
},
{
"category": {
"id": 2,
"name": "category 2"
},
"tasks": []
}
]
},
{
"date": "2025-03-31",
"categories": [
{
"category": {
"id": 1,
"name": "BA Basic"
},
"tasks": []
},
{
"category": {
"id": 2,
"name": "category 2"
},
"tasks": []
}
]
},
{
"date": "2025-04-01",
"categories": [
{
"category": {
"id": 1,
"name": "BA Basic"
},
"tasks": []
},
{
"category": {
"id": 2,
"name": "category 2"
},
"tasks": []
}
]
},
{
"date": "2025-04-02",
"categories": [
{
"category": {
"id": 1,
"name": "BA Basic"
},
"tasks": [
{
"id": 2,
"name": …
```
=> Refactor [#175] 할일 카드 단일로 조회되도록 변경

morib/src/main/java/org/morib/server/api/homeView/facade/HomeViewFacade.java, morib/src/main/java/org/morib/server/api/timerView/dto/TimerResponseDto.java, morib/src/main/java/org/morib/server/api/timerView/dto/UpdateTimerSessionDto.java, morib/src/main/java/org/morib/server/api/timerView/facade/TimerViewFacade.java, morib/src/main/java/org/morib/server/domain/timer/TimerSessionManager.java, morib/src/main/java/org/morib/server/global/message/ErrorMessage.java, morib/src/main/java/org/morib/server/scheduler/TimerScheduler.java, morib/src/test/java/org/morib/server/facade/TimerMultiUserIntegrationTest.java
- closes #189 
- 리뷰를 반영해서 다중 파라미터를 별개의 dto로 분리했어요.
- 도메인 레이어 안에서도 엔티티 내부와는 의존이 이어지지 않도록 Manager에서 dto를 풀어서 진입하도록 했어요.
```java
// Dto
public record UpdateTimerSessionDto(
String runningCategoryName,
Task selectedTask,
int elapsedTime,
TimerStatus timerStatus,
LocalDate targetDate
) {
public static UpdateTimerSessionDto of(String runningCategoryName, Task selectedTask, int elapsedTime, TimerStatus timerStatus, LocalDate targetDate) {
return new UpdateTimerSessionDto(runningCategoryName, selectedTask, elapsedTime, timerStatus, targetDate);
}
}
// Manager
public void updateTimerSession(TimerSession timerSession, UpdateTimerSessionDto updateTimerSessionDto) {
timerSession.update(
updateTimerSessionDto.runningCategoryName(),
updateTimerSessionDto.selectedTask(), …
```
=> Refactor [#189] 리뷰 반영하여 Dto 분리 및 누락된 응답 필드 추가

morib/src/main/java/org/morib/server/global/config/CustomAuthorizationRequestResolver.java, morib/src/main/java/org/morib/server/global/config/SecurityConfig.java, morib/src/main/java/org/morib/server/global/oauth2/handler/OAuth2LoginSuccessHandler.java
=> Feat [#199] 

morib/src/main/java/org/morib/server/api/allowGroupView/facade/AllowedGroupViewFacade.java, morib/src/main/java/org/morib/server/global/common/util/UrlUtils.java
=> Refactor [#202] 허용 서비스 추가 시 유효하지 않은 경우 핸들링 로직 추가

morib/src/main/java/org/morib/server/global/common/util/UrlUtils.java
=> Refactor [#202] 허용 서비스 추출 실패 시 사이트 이름 정보 .com 지우기

morib/src/main/java/org/morib/server/global/common/S3Info.java, morib/src/main/java/org/morib/server/global/common/S3Service.java
=> Feat [#210] S3 발급 로직 추가

.github/workflows/CD.yml, morib/.gitignore, morib/build.gradle, morib/src/main/java/org/morib/server/api/loginView/controller/UserAuthController.java, morib/src/main/java/org/morib/server/api/loginView/facade/UserAuthFacade.java, morib/src/main/java/org/morib/server/domain/user/infra/type/Platform.java, morib/src/main/java/org/morib/server/global/common/Constants.java, morib/src/main/java/org/morib/server/global/config/AppleProperties.java, morib/src/main/java/org/morib/server/global/config/SecurityConfig.java, morib/src/main/java/org/morib/server/global/oauth2/OAuthAttributes.java, morib/src/main/java/org/morib/server/global/oauth2/converter/CustomRequestEntityConverter.java, morib/src/main/java/org/morib/server/global/oauth2/service/CustomOAuth2UserService.java, morib/src/main/java/org/morib/server/global/oauth2/userinfo/AppleOAuth2UserInfo.java
애플 소셜 로그인 구현
이슈는 해당 구현 deploy 환경에서 테스트 이후 완료되면 닫도록 하겠습니다!
=> apple 소셜 로그인을 구현하기 위한 과정을 진행하였어요.

morib/src/main/java/org/morib/server/global/config/CustomAuthorizationRequestResolver.java, morib/src/main/java/org/morib/server/global/oauth2/converter/CustomRequestEntityConverter.java
resolver에서 google 강제 Redirection apple일 경우 apple로 갈 수 있도록 변경
=> fix: resolver에서 google 강제 Redirection apple일 경우 apple로 갈 수 있도록 변경

morib/src/main/java/org/morib/server/global/config/CustomAuthorizationRequestResolver.java, morib/src/main/java/org/morib/server/global/oauth2/converter/CustomRequestEntityConverter.java
로깅 추가 및 requestUri yml에 정의한 대로 받을 수 있도록 수정
=> fix: 로깅 추가 및 requestUri yml에 정의한 대로 받을 수 있도록 수정

morib/src/main/java/org/morib/server/global/oauth2/service/CustomOAuth2UserService.java
apple 로그인, 이외 소셜 로그인 구분 진행, 로깅 추가 진행
=> fix: apple 로그인, 이외 소셜 로그인 구분 진행, 로깅 추가 진행

morib/src/main/java/org/morib/server/global/oauth2/service/CustomOAuth2UserService.java, morib/src/main/java/org/morib/server/global/oauth2/userinfo/AppleOAuth2UserInfo.java
userRequest 응답을 보고 판단하기 위한 로깅 작성 진행 및 email로 우선 이름 지정하는 로직 구현
=> userRequest 응답을 보고 판단하기 위한 로깅 작성 진행 및 email로 우선 이름 지정하는 로직 구현

morib/src/main/java/org/morib/server/global/config/CustomAuthorizationRequestResolver.java
=> fix: session 을 잃지 않도록 state 설정 진행

morib/src/main/java/org/morib/server/global/config/CustomAuthorizationRequestResolver.java, morib/src/main/java/org/morib/server/global/oauth2/handler/OAuth2LoginSuccessHandler.java
=> fix: successHandler log 남기기 작업 진행

morib/src/main/java/org/morib/server/global/config/SecurityConfig.java, morib/src/main/java/org/morib/server/global/oauth2/converter/AppleOAuth2AccessTokenResponseClient.java, morib/src/main/java/org/morib/server/global/oauth2/converter/AppleTokenHolder.java, morib/src/main/java/org/morib/server/global/oauth2/converter/CompositeOAuth2AccessTokenResponseClient.java
apple에서 refreshToken 가져올 수 있도록 변경 진행
=> feat: apple에서 refreshToken 가져올 수 있도록 변경 진행

morib/src/main/java/org/morib/server/global/oauth2/converter/AppleOAuth2AccessTokenResponseClient.java, morib/src/main/java/org/morib/server/global/oauth2/converter/CompositeOAuth2AccessTokenResponseClient.java, morib/src/main/java/org/morib/server/global/oauth2/handler/OAuth2LoginSuccessHandler.java, morib/src/main/java/org/morib/server/global/oauth2/service/CustomOAuth2UserService.java
-  social_refresh_token 저장되는지 확인하기 위한 로깅 로직 추가
=> chore: social_refresh_token 저장되는지 확인하기 위한 로깅 로직 추가

morib/src/main/java/org/morib/server/global/oauth2/converter/AppleOAuth2AccessTokenResponseClient.java, morib/src/main/java/org/morib/server/global/oauth2/handler/OAuth2LoginSuccessHandler.java, morib/src/main/java/org/morib/server/global/oauth2/service/CustomOAuth2UserService.java, morib/src/main/java/org/morib/server/global/oauth2/userinfo/AppleOAuth2UserInfo.java
refresh_token 전달 방식 변경에 따른 저장 방식 변경
=> fix: refresh_token 전달 방식 변경에 따른 저장 방식 변경

morib/src/main/java/org/morib/server/global/oauth2/converter/AppleOAuth2AccessTokenResponseClient.java
- parameter map 하나에 다 담을 수 있도록 변경
=> fix: map 하나에 다 담을 수 있도록 변경

morib/src/main/java/org/morib/server/global/oauth2/handler/OAuth2LoginSuccessHandler.java, morib/src/main/java/org/morib/server/global/oauth2/service/CustomOAuth2UserService.java
=> fix: refreshToken 방식 변경(현재 구현중)

morib/src/main/java/org/morib/server/global/oauth2/service/CustomOAuth2UserService.java
=> fix: restClient 방식으로 변경

morib/src/main/java/org/morib/server/global/oauth2/service/CustomOAuth2UserService.java
=> fix: 실패 로직을 확인하기 위한 로깅 추가

morib/src/main/java/org/morib/server/global/oauth2/service/CustomOAuth2UserService.java
=> fix: 상세 에러를 확인하기 위한 에러 메시지 추가

morib/src/main/java/org/morib/server/global/oauth2/service/CustomOAuth2UserService.java
추가 로직 변경 진행 url 전송 로직 수정 및 로깅 추가
=> fix: 추가 로직 변경 진행 url 전송 로직 수정 및 로깅 추가

morib/src/main/java/org/morib/server/global/config/CustomAuthorizationRequestResolver.java, morib/src/main/java/org/morib/server/global/oauth2/handler/OAuth2LoginSuccessHandler.java
동일한 빈 사용해서 request 처리할 수 있도록 변경
=> fix: 동일한 빈 사용해서 request 처리할 수 있도록 변경

morib/src/main/java/org/morib/server/global/oauth2/handler/OAuth2LoginSuccessHandler.java
=> fix: 순환의존성 해결을 위해 lazy 사용

morib/src/main/java/org/morib/server/global/config/CustomAuthorizationRequestResolver.java, morib/src/main/java/org/morib/server/global/oauth2/handler/OAuth2LoginSuccessHandler.java, morib/src/main/java/org/morib/server/global/oauth2/service/CustomOAuth2UserService.java
=> chore: 로그 추가 진행

morib/src/main/java/org/morib/server/global/config/CustomAuthorizationRequestResolver.java, morib/src/main/java/org/morib/server/global/oauth2/converter/CustomRequestEntityConverter.java, morib/src/main/java/org/morib/server/global/oauth2/handler/OAuth2LoginSuccessHandler.java
logging에 state original로 설정하여 진행
=> fix: logging에 state original로 설정하여 진행

morib/src/main/java/org/morib/server/global/oauth2/handler/OAuth2LoginSuccessHandler.java
remove request에서 없애고 난 다음 확인하기 위한 수정
=> fix: remove request에서 없애고 난 다음 확인하기 위한 수정

morib/src/main/java/org/morib/server/global/config/DebugOAuth2AuthorizationRequestRepository.java, morib/src/main/java/org/morib/server/global/config/SecurityConfig.java, morib/src/main/java/org/morib/server/global/oauth2/handler/OAuth2LoginSuccessHandler.java
제대로된 로깅을 보기 위한 클래스 상속받아서 로깅 진행
=> fix : 제대로된 로깅을 보기 위한 클래스 상속받아서 로깅 진행
