morib-in/Morib-Server-v2

morib/src/main/java/org/morib/server/api/homeViewApi/controller/HomeViewController.java, morib/src/main/java/org/morib/server/api/homeViewApi/service/FetchService.java, morib/src/main/java/org/morib/server/api/homeViewApi/service/HomeViewFacade.java, morib/src/main/java/org/morib/server/api/homeViewApi/service/fetch/HomeViewFacade.java, morib/src/main/java/org/morib/server/api/homeViewApi/service/fetch/home/FetchHomeService.java, morib/src/main/java/org/morib/server/api/homeViewApi/service/fetch/home/FetchHomeServiceImpl.java, morib/src/main/java/org/morib/server/api/homeViewApi/service/fetch/timer/FetchUserTimerService.java, morib/src/main/java/org/morib/server/api/homeViewApi/service/fetch/timer/FetchUserTimerServiceImpl.java, morib/src/main/java/org/morib/server/domain/category/Category.java, morib/src/main/java/org/morib/server/domain/category/CategoryReader.java, morib/src/main/java/org/morib/server/domain/category/infra/Category.java, morib/src/main/java/org/morib/server/domain/category/infra/CategoryEntity.java, morib/src/main/java/org/morib/server/domain/task/TaskReader.java, morib/src/main/java/org/morib/server/domain/task/infra/Task.java, morib/src/main/java/org/morib/server/domain/task/infra/TaskRepository.java, morib/src/main/java/org/morib/server/domain/timer/TimerAggregator.java, morib/src/main/java/org/morib/server/domain/timer/TimerReader.java, morib/src/main/java/org/morib/server/domain/timer/infra/Timer.java, morib/src/main/java/org/morib/server/domain/timer/infra/TimerRepository.java
- closes #3 
1. 홈뷰 전체조회, 오늘 나의 작업시간 조회 API 스켈레톤 코드 구현했습니다.
2. service 패키지의 fetch 패키지를 home, timer로 분리했습니다. 그에 따라, Service 인터페이스와 구현체 네이밍을 구체화해두었습니다.
- 지금 제가 작성한 구조는 Facade에서는 Service 인터페이스만을 알고 있고, Service 인터페이스도 실제 로직의 구조 자체를 모르도록 execute() 메소드로 추상화되어있습니다. 그에 따라 ServiceImpl에서 각 엔티티를 가져오는 도메인 클래스인 Reader들을 의존받아 로직을 구성하도록 작성해두었습니다. -> 요 구조가 회의에서 결정된 구조가 맞는지, 올바른 방법인지 잘 모르겠습니다.
코드를 작성하다보니 회의에서 결정된 구조가 맞는 것인지 잘 모르겠어서 일부 구현한 코드를 리뷰 받고 나머지 작업을 진행하려고 합니다 ! :)
=> Feat [#3] 홈뷰 스켈레톤 코드 일부 구현

morib/src/main/java/org/morib/server/domain/allowedSite/infra/AllowedSite.java, morib/src/main/java/org/morib/server/domain/category/infra/Category.java, morib/src/main/java/org/morib/server/domain/relationship/infra/Relationship.java, morib/src/main/java/org/morib/server/domain/task/infra/Task.java, morib/src/main/java/org/morib/server/domain/timer/infra/Timer.java, morib/src/main/java/org/morib/server/domain/todo/infra/Todo.java, morib/src/main/java/org/morib/server/domain/user/infra/User.java, morib/src/main/java/org/morib/server/global/common/ApiResponseUtil.java, morib/src/main/java/org/morib/server/global/common/BaseResponse.java, morib/src/main/java/org/morib/server/global/common/BaseTimeEntity.java, morib/src/main/java/org/morib/server/global/config/JpaAuditingConfig.java, morib/src/main/java/org/morib/server/global/message/ErrorMessage.java, morib/src/main/java/org/morib/server/global/message/SuccessMessage.java
- closes #21 
- ApiResponseUtil, BaseResponse 추가했습니다.
- ErrorMessage, SuccessMessage에 code는 제외했습니다. 추가로, 200과 400 하나씩만 넣어두었습니다.
- JpaAuditingConfig, BaseTimeEntity 추가했습니다. 
- 엔티티에 Auditing 적용했습니다.
패키지 괜찮은지 ?? 일단 global 패키지 만들고 넣어두었습니다..!
=> Feat [#21] Api 응답 클래스, Auditing 구현

morib/build.gradle, morib/src/main/java/org/morib/server/api/homeView/controller/HomeViewController.java, morib/src/main/java/org/morib/server/api/homeView/controller/TaskController.java, morib/src/main/java/org/morib/server/api/modalView/controller/CategoryController.java, morib/src/main/java/org/morib/server/api/modalView/controller/ModalViewController.java, morib/src/main/java/org/morib/server/api/timerView/controller/TimerViewController.java, morib/src/main/java/org/morib/server/api/timerView/facade/TimerViewFacade.java, morib/src/main/java/org/morib/server/domain/user/application/FetchUserService.java, morib/src/main/java/org/morib/server/domain/user/infra/User.java, morib/src/main/java/org/morib/server/domain/user/infra/UserRepository.java, morib/src/main/java/org/morib/server/domain/user/infra/type/Role.java, morib/src/main/java/org/morib/server/global/common/BaseResponse.java, morib/src/main/java/org/morib/server/global/common/Constants.java, morib/src/main/java/org/morib/server/global/common/TokenResponseDto.java, morib/src/main/java/org/morib/server/global/config/SecurityConfig.java, morib/src/main/java/org/morib/server/global/config/WebSecurityConfig.java, morib/src/main/java/org/morib/server/global/jwt/CustomJwtAuthenticationEntryPoint.java, morib/src/main/java/org/morib/server/global/jwt/JwtAuthenticationFilter.java, morib/src/main/java/org/morib/server/global/jwt/JwtService.java, morib/src/main/java/org/morib/server/global/message/ErrorMessage.java, morib/src/main/java/org/morib/server/global/oauth2/CustomOAuth2User.java, morib/src/main/java/org/morib/server/global/oauth2/OAuthAttributes.java, morib/src/main/java/org/morib/server/global/oauth2/handler/OAuth2LoginFailureHandler.java, morib/src/main/java/org/morib/server/global/oauth2/handler/OAuth2LoginSuccessHandler.java, morib/src/main/java/org/morib/server/global/oauth2/service/CustomOAuth2UserService.java, morib/src/main/java/org/morib/server/global/oauth2/userinfo/GoogleOAuth2UserInfo.java, morib/src/main/java/org/morib/server/global/oauth2/userinfo/OAuth2UserInfo.java, morib/src/main/java/org/morib/server/global/userauth/CustomUserAuthentication.java, morib/src/main/java/org/morib/server/global/userauth/CustomUserDetails.java, morib/src/main/java/org/morib/server/global/userauth/PrincipalHandler.java
- closes #57 
- JwtService 메서드 분리해서 가독성 높였습니다.
- @Value로 yaml 참조하게 변경했습니다.
- 기존 Jwt 빌딩 방식을 jjwt로 변경했습니다. (Jwts.~) 
- Attributes 클래스에서 toEntity 하는 코드를 User의 정적 팩토리 메소드로 변경했습니다.
- 에러 처리는 다 커스텀으로 변경이 안 된 것 같습니다 ,, 조금씩 보입니다 ,, 죄송 ,,
- 불필요한 공백, 주석 전부 제거했습니다.
- AuthenticationPrincipal 전면 적용했습니다. PrincipalHandler에 CustomUserDetails 객체를 userId로 뽑아오는 코드 넣어줬습니다.
- indentation, depth 보이는 건 깔끔하게 정리했습니다.
커밋을 최대한 작업별로 나눠보려고 했는데도 많이 크네요 ,, ㅠㅋㅋ
패키지를 진짜 어떻게 해야할지 고민입니다. 한번 같이 논의해보시죠 ..
=> Feat [#57] 구글 소셜 로그인, Spring Security 전면 적용

morib/src/main/java/org/morib/server/api/homeView/dto/fetch/HomeViewResponseDto.java, morib/src/main/java/org/morib/server/api/homeView/facade/HomeViewFacade.java, morib/src/main/java/org/morib/server/api/homeView/vo/CategoryInfo.java, morib/src/main/java/org/morib/server/api/homeView/vo/TaskInfo.java, morib/src/main/java/org/morib/server/api/modalView/dto/CreateCategoryRequestDto.java, morib/src/main/java/org/morib/server/api/modalView/facade/ModalViewFacade.java, morib/src/main/java/org/morib/server/api/modalView/vo/AllowedSiteInfo.java, morib/src/main/java/org/morib/server/domain/category/application/CreateCategoryService.java, morib/src/main/java/org/morib/server/domain/category/application/CreateCategoryServiceImpl.java, morib/src/main/java/org/morib/server/domain/category/infra/Category.java
- closes #62 
카테고리 startDate, endDate 로직에서 제외했습니다.
엔티티에서는 startDate nullable로 풀어준 후, null로 들어가도록 create 정적 팩토리 메서드에서 파라미터 제외했습니다.
TaskInfo targetTime -> `elapsedTime` 으로 수정했습니다.
allowedSiteInfo 생성했습니다. allowedSite의 모든 필드가 아닌 name, url만 받기도 하고, request로 들어올 때 siteName, siteUrl이 아닌 원래의 api 명세 대로 들어올 수 있게 새로 dto 생성해서 처리했습니다.
HomeViewFacade 로직 변경이 큰데, 하다보니 헷갈려서 주석처리로 설명 써뒀습니다. 추후 기획 요구사항 픽스되면 제거하겠습니다.
AllowedSite라고 된 것도 있고 AllowSite라고 된 것도 있더라구요! 네이밍 정리를 하면 좋을 듯 싶습니다.
PR이 좀 크네요 ,, 천천히 보시고 리뷰해주시면 감사하겠습니다 :) !!
=> Refactor [#62] 카테고리 start, endDate 삭제로 인한 로직 수정

morib/.gitignore, morib/src/main/java/org/morib/server/MoribApplication.java, morib/src/main/java/org/morib/server/api/loginView/controller/UserAuthController.java, morib/src/main/java/org/morib/server/api/loginView/dto/UserReissueRequestDto.java, morib/src/main/java/org/morib/server/api/loginView/facade/UserAuthFacade.java, morib/src/main/java/org/morib/server/domain/user/UserManager.java, morib/src/main/java/org/morib/server/domain/user/application/dto/ReissueTokenServiceDto.java, morib/src/main/java/org/morib/server/domain/user/application/service/DeleteUserService.java, morib/src/main/java/org/morib/server/domain/user/application/service/DeleteUserServiceImpl.java, morib/src/main/java/org/morib/server/domain/user/application/service/ReissueTokenService.java, morib/src/main/java/org/morib/server/domain/user/application/service/ReissueTokenServiceImpl.java, morib/src/main/java/org/morib/server/domain/user/infra/User.java, morib/src/main/java/org/morib/server/global/common/Constants.java, morib/src/main/java/org/morib/server/global/config/CustomAuthorizationRequestResolver.java, morib/src/main/java/org/morib/server/global/config/SecurityConfig.java, morib/src/main/java/org/morib/server/global/jwt/JwtService.java, morib/src/main/java/org/morib/server/global/message/ErrorMessage.java, morib/src/main/java/org/morib/server/global/oauth2/CustomOAuth2User.java, morib/src/main/java/org/morib/server/global/oauth2/handler/CustomLogoutHandler.java, morib/src/main/java/org/morib/server/global/oauth2/handler/CustomLogoutSuccessHandler.java, morib/src/main/java/org/morib/server/global/oauth2/handler/OAuth2LoginSuccessHandler.java, morib/src/main/java/org/morib/server/global/oauth2/service/CustomOAuth2UserService.java
- closes #102 
인증 관련 작업 전부 진행했습니다.
회원 탈퇴의 경우 Spring Security에서 지원하지 않아서 RestTemplate로 구글 api로 revoke 진행했습니다.
=> Feat [#102] 로그아웃, 회원탈퇴, 토큰 재발급 api 구현

morib/src/main/java/org/morib/server/api/homeView/facade/HomeViewFacade.java, morib/src/main/java/org/morib/server/api/modalView/facade/ModalViewFacade.java, morib/src/main/java/org/morib/server/api/timerView/dto/StopTimerRequestDto.java, morib/src/main/java/org/morib/server/api/timerView/facade/TimerViewFacade.java, morib/src/main/java/org/morib/server/domain/relationship/application/FetchRelationshipService.java, morib/src/main/java/org/morib/server/domain/relationship/application/FetchRelationshipServiceImpl.java, morib/src/main/java/org/morib/server/domain/timer/application/CreateTimerService.java, morib/src/main/java/org/morib/server/domain/timer/application/CreateTimerServiceImpl.java, morib/src/main/java/org/morib/server/domain/timer/application/FetchTimerService.java, morib/src/main/java/org/morib/server/domain/timer/application/FetchTimerServiceImpl.java, morib/src/main/java/org/morib/server/domain/timer/infra/Timer.java, morib/src/main/java/org/morib/server/domain/timer/infra/TimerRepository.java, morib/src/main/java/org/morib/server/global/common/Constants.java, morib/src/main/java/org/morib/server/global/common/HealthCheckController.java, morib/src/main/java/org/morib/server/global/jwt/JwtAuthenticationFilter.java, morib/src/main/java/org/morib/server/global/message/SseMessageBuilder.java, morib/src/main/java/org/morib/server/global/sse/api/SseController.java, morib/src/main/java/org/morib/server/global/sse/api/SseEventHandler.java, morib/src/main/java/org/morib/server/global/sse/api/SseFacade.java, morib/src/main/java/org/morib/server/global/sse/api/UserInfoDtoForSseUserInfoWrapper.java, morib/src/main/java/org/morib/server/global/sse/application/event/SseDisconnectEvent.java, morib/src/main/java/org/morib/server/global/sse/application/event/SseTimeoutEvent.java, morib/src/main/java/org/morib/server/global/sse/application/repository/SseRepository.java, morib/src/main/java/org/morib/server/global/sse/application/repository/SseUserInfoWrapper.java, morib/src/main/java/org/morib/server/global/sse/application/service/SseSender.java, morib/src/main/java/org/morib/server/global/sse/application/service/SseService.java
- closes #113 
- SSE 관련 클래스 아키텍처 리팩토링했습니다.
- SseController -> SseFacade -> SseService, SseSender -> SseRepository 형태의 아키텍처로 구성했습니다.
- SseRepository에서의 completion, timout 핸들러를 EventPublisher 형태로 이벤트를 발행한 뒤, Facade와 같은 계층의 EventHandler에서 핸들링하여 의존성이 역전되지 않도록 구성했습니다.
- Event Message 또한 요청 별로 구체화하여 업데이트 해두었습니다.
- 할일 추가 후 타이머 시작 api에서 Timer가 생성되는 로직이 빠져있어 추가했습니다.
=> Refactor [#113] SSE 관련 클래스 아키텍처 리팩토링

morib/src/main/java/org/morib/server/api/homeView/controller/HomeViewController.java, morib/src/main/java/org/morib/server/api/homeView/facade/HomeViewFacade.java, morib/src/main/java/org/morib/server/api/homeView/vo/CombinedCategoryAndTaskInfo.java, morib/src/main/java/org/morib/server/domain/category/infra/CategoryRepository.java, morib/src/main/java/org/morib/server/domain/task/application/ClassifyTaskService.java, morib/src/main/java/org/morib/server/domain/task/application/ClassifyTaskServiceImpl.java
- closes #115 
홈뷰 전체조회 api 리팩토링했습니다.
- distinct, fetch-join으로 N+1 해결하면서 로직 단순화했습니다.
- order by로 생성된 시점 기준으로 내림차순 정렬했습니다.
- endDate가 null인 경우 끝나는 시점이 없도록 핸들링하는 방향으로 로직 수정했습니다.
=> Refactor [#115] 홈뷰 전체조회 리팩토링

morib/src/main/java/org/morib/server/api/timerView/controller/TimerViewController.java, morib/src/main/java/org/morib/server/api/timerView/dto/AssignAllowedGroupsRequestDto.java, morib/src/main/java/org/morib/server/api/timerView/dto/FetchAllowedGroupInTimerResponseDto.java, morib/src/main/java/org/morib/server/api/timerView/dto/TaskInTodoCardDto.java, morib/src/main/java/org/morib/server/domain/allowedGroup/infra/AllowedGroupManager.java, morib/src/main/java/org/morib/server/domain/recentAllowedGroup/application/CreateRecentAllowedGroupService.java, morib/src/main/java/org/morib/server/domain/recentAllowedGroup/application/DeleteRecentAllowedGroupService.java, morib/src/main/java/org/morib/server/domain/recentAllowedGroup/application/FetchRecentAllowedGroupService.java, morib/src/main/java/org/morib/server/domain/recentAllowedGroup/application/impl/CreateRecentAllowedGroupServiceImpl.java, morib/src/main/java/org/morib/server/domain/recentAllowedGroup/application/impl/DeleteRecentAllowedGroupServiceImpl.java, morib/src/main/java/org/morib/server/domain/recentAllowedGroup/application/impl/FetchRecentAllowedGroupServiceImpl.java, morib/src/main/java/org/morib/server/domain/recentAllowedGroup/infra/RecentAllowedGroup.java, morib/src/main/java/org/morib/server/domain/recentAllowedGroup/infra/RecentAllowedGroupRepository.java
- closes #119 
타이머 상단 허용 서비스 조회, 등록 API 구현했습니다.
타이머 내에서 최근 선택한 허용 서비스를 아카이빙하기 위한 RecentAllowedGroup Entity 생성했습니다. AllowedGroup이 사라지면 같이 사라질 수 있도록 1:1 Cascade 설정했습니다.
=> Feat [#119] 타이머 상단 허용 서비스 조회, 등록 API 구현

morib/src/main/java/org/morib/server/api/homeView/facade/HomeViewFacade.java, morib/src/main/java/org/morib/server/api/timerView/dto/StopTimerRequestDto.java, morib/src/main/java/org/morib/server/domain/category/application/FetchCategoryService.java, morib/src/main/java/org/morib/server/domain/category/application/FetchCategoryServiceImpl.java, morib/src/main/java/org/morib/server/domain/task/application/FetchTaskService.java, morib/src/main/java/org/morib/server/domain/task/application/FetchTaskServiceImpl.java, morib/src/main/java/org/morib/server/domain/task/infra/TaskRepository.java, morib/src/main/java/org/morib/server/domain/timer/application/FetchTimerService.java, morib/src/main/java/org/morib/server/domain/timer/application/FetchTimerServiceImpl.java, morib/src/main/java/org/morib/server/domain/todo/TodoManager.java, morib/src/main/java/org/morib/server/domain/todo/infra/Todo.java, morib/src/main/java/org/morib/server/domain/user/infra/User.java
- closes #127 
[기존 할일 카드 조회 시, 해당하는 태스크들의 순서가 계속 바뀌는 이슈]
Todo가 Set<Task> 형태로 연관관계를 맺고 있었기 때문에, 타이머 진입 시에 클라이언트에서 전달했던 순서가 유지되지 않았어요.
- 이를 위해, `@OrderColumn`을 이용한 조인 테이블에 인덱스를 생성했고 타입을 List<Task>로 변경했습니다.
- 추가적으로 지연 로딩 이슈 해결을 위한 Fetch Join 쿼리 추가했습니다.
=> Refactor [#127] 할일 카드 조회 시 태스크 정렬을 위한 타입 마이그레이션

morib/src/main/java/org/morib/server/api/allowGroupView/facade/AllowedGroupViewFacade.java, morib/src/main/java/org/morib/server/global/common/Constants.java, morib/src/main/java/org/morib/server/global/message/ErrorMessage.java, morib/src/main/java/org/morib/server/global/message/SseMessageBuilder.java, morib/src/main/java/org/morib/server/global/sse/api/SseController.java, morib/src/main/java/org/morib/server/global/sse/api/SseEventHandler.java, morib/src/main/java/org/morib/server/global/sse/api/SseFacade.java, morib/src/main/java/org/morib/server/global/sse/application/event/SseHeartbeatEvent.java, morib/src/main/java/org/morib/server/global/sse/application/repository/SseRepository.java, morib/src/main/java/org/morib/server/global/sse/application/service/SseSender.java, morib/src/main/java/org/morib/server/global/sse/application/service/SseService.java
- closes #135 
- SSE Refresh 과도하게 발생
heart-beat, reconnectTime을 설정해 과도하게 발생하는 refresh를 최소화했습니다.
- NPE 핸들링
Emitter가 존재하지 않는 경우 send 시 NPE 발생할 수 있기 때문에 if문으로 분기처리했습니다.
- 허용 서비스 등록 시 프로토콜 자동 등록하는 로직 추가했습니다.
=> Refactor [#135] SSE 관련 리팩토링

morib/src/main/java/org/morib/server/api/loginView/controller/UserAuthController.java, morib/src/main/java/org/morib/server/api/loginView/facade/UserAuthFacade.java, morib/src/main/java/org/morib/server/domain/user/application/service/ReissueTokenServiceImpl.java, morib/src/main/java/org/morib/server/global/jwt/JwtAuthenticationFilter.java, morib/src/main/java/org/morib/server/global/jwt/JwtService.java, morib/src/main/java/org/morib/server/global/oauth2/handler/OAuth2LoginSuccessHandler.java
- closes #137 
- 토큰 재발급 시 authorization 헤더에 만료된 atk 주입 코드 제거했습니다. 어플리케이션 로직 진입 전에 filter에서 거르기 때문에 빠른 개발을 위해 제외했습니다.
- reissue 관련 검증 로직 추가했습니다. 
- 회원 탈퇴 시, relationship을 수동으로 끊어주는 로직 추가했습니다.
=> Refactor [#137] 토큰 재발급, 인증 관련 이슈 해결

morib/src/main/java/org/morib/server/api/allowGroupView/dto/FetchAllowedGroupListResponseDto.java, morib/src/main/java/org/morib/server/api/allowGroupView/facade/AllowedGroupViewFacade.java
- closes #139 
- QA Notion Link : https://www.notion.so/1a997d212fa280e9aabdc8e3004c8224?pvs=4
- 허용 서비스 조회 시 컬러 팔레트 바꿀때마다 좌측 파비콘 정렬 바뀜 이슈를 해결했습니다.
- 정렬 로직이 명시되어있지 않아 AllowedGroup 상새조회 정렬 로직 extract 후 재사용해 수정했습니다.
- 중복 제거는 최상위 도메인을 추출하여 비교하기 때문에 아이콘이 다른데도 제거해버릴 수 있어서 2차 QA 후 이슈 있으면 수정하겠습니다.
=> Refactor [#139] 허용 서비스 리스트 조회 로직 수정

morib/src/main/java/org/morib/server/global/oauth2/handler/OAuth2LoginFailureHandler.java
- closes #147 
- response.getWriter로 바로 화면에 텍스트를 표시했는데, 인코딩이 빠져 물음표로 보이는 문제가 있었습니다.
https://github.com/morib-in/Morib-Server-v2/blob/b298359c3541aa8a2134d89dc10dcd5e20114a3f/morib/src/main/java/org/morib/server/global/oauth2/handler/OAuth2LoginFailureHandler.java#L18-L22
실패 시 실행되는 OAuth2LoginFailureHandler의 Response에 UTF 인코딩을 적용해 해결했습니다.
=> Refactor [#147] Response에 UTF-8 인코딩 적용 - QA 반영

morib/Dockerfile, morib/src/main/java/org/morib/server/global/common/Constants.java, morib/src/main/java/org/morib/server/global/config/SecurityConfig.java, morib/src/main/java/org/morib/server/global/sse/api/SseController.java, morib/src/main/java/org/morib/server/global/sse/api/SseFacade.java, morib/src/main/java/org/morib/server/global/sse/application/repository/SseRepository.java, morib/src/main/java/org/morib/server/global/sse/application/service/SseSender.java
- closes #153 
<br>
SseEmitter 관련 메모리 누수 문제를 해결하기 위한 여러 개선 사항을 적용했어요.
- 동일한 사용자의 새 연결 요청 시 기존 연결을 명시적으로 제거하는 로직을 추가했습니다.
https://github.com/morib-in/Morib-Server-v2/blob/00a8ebcb0d8a378a03b6e2d611da6d18c9100b28/morib/src/main/java/org/morib/server/global/sse/application/repository/SseRepository.java#L142-L155
- SseEmitter에 등록하는 콜백을 개선하여 모든 상황에서 리소스를 정리하도록 했습니다.
- onError 콜백을 추가하여 예외 상황에서도 리소스를 정리합니다.
https://github.com/morib-in/Morib-Server-v2/blob/00a8ebcb0d8a378a03b6e2d611da6d18c9100b28/morib/src/main/java/org/morib/server/global/sse/application/repository/SseRepository.java#L50-L69
- 주기적으로 오래된 연결을 정리하는 스케줄러를 추가했습니다.
- 연결 시간이 MAX_CONNECTION_TIME을 초과하면 제거합니다.
https://github.com/morib-in/Morib-Server-v2/blob/00a8ebcb0d8a378a03b6e2d611da6d18c9100b28/morib/src/main/java/org/morib/server/glob …
=> Fix [#153] SSE 구현 개선 및 메모리 누수 해결

morib/src/main/java/org/morib/server/MoribApplication.java, morib/src/main/java/org/morib/server/domain/user/application/service/ReissueTokenServiceImpl.java, morib/src/main/java/org/morib/server/global/sse/api/SseController.java, morib/src/main/java/org/morib/server/global/sse/api/SseMonitorController.java, morib/src/main/java/org/morib/server/global/sse/application/repository/SseMemoryMonitor.java, morib/src/main/java/org/morib/server/global/sse/application/repository/SseRepository.java, morib/src/main/java/org/morib/server/global/sse/application/service/SseService.java
- closes #155 
SSE 관련 메모리 이슈로 인한 어드민과 모니터링 로직을 추가했어요.
- 현재 메모리 사용량 및 SSE 연결 정보 조회
https://github.com/morib-in/Morib-Server-v2/blob/8713a3d19d168b209859d8ebb584c0842c125abf/morib/src/main/java/org/morib/server/global/sse/api/SseMonitorController.java#L32-L36
- 가비지 컬렉션 수동 실행 및 결과 반환
https://github.com/morib-in/Morib-Server-v2/blob/8713a3d19d168b209859d8ebb584c0842c125abf/morib/src/main/java/org/morib/server/global/sse/api/SseMonitorController.java#L51-L66
- 1분 간격으로 메모리 사용량 및 SSE 연결 상태 로깅
- 각 연결의 세부 정보(ID, 카테고리, 경과 시간) 로깅
https://github.com/morib-in/Morib-Server-v2/blob/8713a3d19d168b209859d8ebb584c0842c125abf/morib/src/main/java/org/morib/server/global/sse/application/repository/SseMemoryMonitor.java#L18-L44
=> Feat [#155] SSE 어드민 api 추가 및 모니터링 로깅 추가

morib/src/main/java/org/morib/server/global/sse/application/repository/SseRepository.java
- closes #157 
SSE 관련 이슈 해결 중, 다음 로그를 확인했습니다.
45초동안 아무 일도 일어나지 않아 계속해서 refresh 요청을 날리는 것 같아, heart-beat 주기를 30초로 단축했습니다.
```java
@Scheduled(fixedRate = 30000)
public void sendHeartbeat() {
eventPublisher.publishEvent(new SseHeartbeatEvent(this));
}
```
=> Fix [#157] sse heartbeat 주기 단축

morib/src/main/java/org/morib/server/global/common/Constants.java, morib/src/main/java/org/morib/server/global/sse/api/SseController.java, morib/src/main/java/org/morib/server/global/sse/api/SseEventHandler.java, morib/src/main/java/org/morib/server/global/sse/application/service/SseSender.java
- closes #159 
이전 PR에서의 문제가 해결되지 않아 추가적으로 변경사항을 반영합니다.
- SSE heart-beat가 클라이언트에게 제대로 인식되지 않을 수 있어, 이벤트 발송이 아닌 comment를 발송하도록 변경했습니다.
```java
public static final String SSE_EVENT_HEARTBEAT = ": heartbeat\n\n";
targetEmitter.send(SseEmitter.event()
.comment(SSE_EVENT_HEARTBEAT));
```
- 기존 refresh 컨트롤러 코드에서 반환 타입이 text/event-stream 방식이 적용되어있지 않아 수정했습니다.
```java
@GetMapping(value = "/sse/refresh", produces = MediaType.TEXT_EVENT_STREAM_VALUE)
```
=> Fix [#159] SSE heart-beat 수정

morib/src/main/java/org/morib/server/api/timerView/facade/TimerViewFacade.java, morib/src/main/java/org/morib/server/domain/todo/application/FetchTodoService.java, morib/src/main/java/org/morib/server/domain/todo/application/FetchTodoServiceImpl.java, morib/src/main/java/org/morib/server/global/common/Constants.java, morib/src/main/java/org/morib/server/global/sse/api/SseController.java, morib/src/main/java/org/morib/server/global/sse/api/SseEventHandler.java, morib/src/main/java/org/morib/server/global/sse/application/repository/SseMemoryMonitor.java, morib/src/main/java/org/morib/server/global/sse/application/service/SseSender.java
- closes #161 
- 오늘 할 일 카드를 조회하는 api에서 조회 결과가 없으면 NPE가 아닌 빈 배열로 리턴되도록 수정했습니다.
```java
public TodoCardResponseDto fetchTodoCard(Long userId, LocalDate targetDate) {
int totalTimeOfToday = fetchTimerService.sumElapsedTimeByUser(fetchUserService.fetchByUserId(userId), targetDate);
Optional<Todo> todo = fetchTodoService.fetchByUserIdAndTargetDate(userId, targetDate);
if (todo.isEmpty()) return new TodoCardResponseDto(totalTimeOfToday, Collections.emptyList());
LinkedHashSet<Task> tasks = fetchTaskService.fetchByTodoAndSameTargetDate(todo.get(), targetDate);
```
- SSE Refresh 로직 시 인코딩 이슈로 인해 `runningCategoryName`은 Query Parameter로 수정했습니다.
```java
@RequestParam("runningCategoryName") String runningCategoryName) {
```
- 가비지 컬렉션을 직접 호출하는 코드는 제거했습니다.
=> Refactor [#161] Todo 및 SSE 관련 변경사항 반영

morib/src/main/java/org/morib/server/api/timerView/facade/TimerViewFacade.java, morib/src/main/java/org/morib/server/domain/category/application/FetchCategoryService.java, morib/src/main/java/org/morib/server/domain/category/application/FetchCategoryServiceImpl.java, morib/src/main/java/org/morib/server/domain/category/infra/CategoryRepository.java, morib/src/main/java/org/morib/server/domain/timer/application/FetchTimerService.java, morib/src/main/java/org/morib/server/domain/timer/application/FetchTimerServiceImpl.java, morib/src/main/java/org/morib/server/domain/timer/infra/TimerRepository.java, morib/src/main/java/org/morib/server/domain/timer/infra/TimerStatus.java, morib/src/main/java/org/morib/server/global/message/ErrorMessage.java, morib/src/main/java/org/morib/server/global/message/SseMessageBuilder.java, morib/src/main/java/org/morib/server/global/sse/api/SseController.java, morib/src/main/java/org/morib/server/global/sse/api/SseFacade.java, morib/src/main/java/org/morib/server/global/sse/api/SseMonitorController.java, morib/src/main/java/org/morib/server/global/sse/api/UserInfoDtoForSseUserInfoWrapper.java, morib/src/main/java/org/morib/server/global/sse/application/repository/SseMemoryMonitor.java, morib/src/main/java/org/morib/server/global/sse/application/repository/SseRepository.java, morib/src/main/java/org/morib/server/global/sse/application/repository/SseUserInfoWrapper.java, morib/src/main/java/org/morib/server/global/sse/application/service/SseSender.java, morib/src/main/java/org/morib/server/global/sse/application/service/SseService.java
- closes #163
SSE 관련 버그 수정했습니다.
- SSE 객체와 UserInfo를 분리했습니다. 연결이 끊겨도 마지막 사용자 정보를 잃지 않도록 했습니다.
```java
// 변경된 SseUserInfoWrapper
public class SseUserInfoWrapper {
private int elapsedTime;
private String runningCategoryName;
private Long taskId;
private TimerStatus timerStatus;
private LocalDateTime lastTimerStatusChangeTime;
// SseRepository
public static final ConcurrentHashMap<Long, SseEmitter> emitters = new ConcurrentHashMap<>();
public static final ConcurrentHashMap<Long, SseUserInfoWrapper> userInfos = new ConcurrentHashMap<>();
```
- 연결 시 이벤트의 동기 처리를 위해 iteration을 추가해 기존 연결이 제거되었는지 확인하고 이벤트를 발송하도록 변경했습니다.
```java
// 기존 연결이 있으면 종료
sseService.removeExistingEmitter(userId);
SseEmitter createdEmitter = sseService.create();
for (int i=0; i<10; i++) {
if …
```
=> Fix [#163] SSE 관련 버그 일체 수정

morib/src/main/java/org/morib/server/api/homeView/controller/TaskController.java, morib/src/main/java/org/morib/server/api/homeView/dto/CreateTaskRequestDto.java, morib/src/main/java/org/morib/server/api/homeView/dto/UpdateTaskRequestDto.java, morib/src/main/java/org/morib/server/api/homeView/facade/HomeViewFacade.java, morib/src/main/java/org/morib/server/domain/task/TaskManager.java, morib/src/main/java/org/morib/server/domain/task/infra/Task.java
- closes #167 
날짜 또는 이름을 선택적으로 수정할 수 있도록 동시에 값을 받도록 했습니다.
`@Valid` + `@NotNull` 을 이용하여 값이 비어있지 않도록 했습니다.
https://github.com/morib-in/Morib-Server-v2/blob/50193f0c9baabf072a7b3c5a00f36ae1cf582d95/morib/src/main/java/org/morib/server/api/homeView/controller/TaskController.java#L39-L44
https://github.com/morib-in/Morib-Server-v2/blob/50193f0c9baabf072a7b3c5a00f36ae1cf582d95/morib/src/main/java/org/morib/server/api/homeView/dto/UpdateTaskRequestDto.java#L9-L11
taskManager를 이용해 조회해 온 Task를 업데이트합니다.
https://github.com/morib-in/Morib-Server-v2/blob/50193f0c9baabf072a7b3c5a00f36ae1cf582d95/morib/src/main/java/org/morib/server/api/homeView/facade/HomeViewFacade.java#L96-L100
더티 체킹으로 엔티티를 업데이트합니다.
https://github.com/morib-in/Morib-Server-v2/blob/50193f0c9baabf072a7b3c5a00f36ae1cf582d95/morib/src/mai …
=> Feat [#167] 할일 카드 수정 api 구현

morib/src/main/java/org/morib/server/api/timerView/facade/TimerViewFacade.java
- closes #171 
- 타이머 하단 친구 목록 조회 시, 필터링과 정렬 기준을 추가했습니다.
- 오늘 할일 몰입 시간이 0인 경우에는 `filter`를 사용해 제외했습니다.
- 온라인 -> 오프라인으로 정렬 후, `thenComparing`을 활용해 이름 오름차순으로 정렬했습니다.
https://github.com/morib-in/Morib-Server-v2/blob/660105bf7067efbab3162bec8e17d899c10f59f9/morib/src/main/java/org/morib/server/api/timerView/facade/TimerViewFacade.java#L114-L121
=> Refactor [#171] 타이머 하단 친구 목록 조회 필터링 추가

morib/src/main/java/org/morib/server/api/allowGroupView/controller/AllowedGroupViewController.java, morib/src/main/java/org/morib/server/domain/allowedSite/application/FetchSiteInfoServiceImpl.java
- closes #179 
`www` 로 시작하지 않는 url일 수도 있으므로 `://`로 구분자 지정해 해결했습니다. 
https://github.com/morib-in/Morib-Server-v2/blob/5eac83bd0af9a939facd90a09c0f577da52565bf/morib/src/main/java/org/morib/server/domain/allowedSite/application/FetchSiteInfoServiceImpl.java#L145
<br>
해당 API에서는 userId 파싱이 필요하지 않으므로 제거했습니다.
https://github.com/morib-in/Morib-Server-v2/blob/f8bb67ee15e9e60361d8e8db2d7547c31451be1a/morib/src/main/java/org/morib/server/api/allowGroupView/controller/AllowedGroupViewController.java#L120
=> Fix [#179] 온보딩 내 URL로 사이트 가져오기 예외 핸들링

morib/src/main/java/org/morib/server/api/allowGroupView/controller/AllowedGroupViewController.java, morib/src/main/java/org/morib/server/api/timerView/facade/TimerViewFacade.java, morib/src/main/java/org/morib/server/domain/allowedSite/application/FetchSiteInfoServiceImpl.java
- closes #181 
타이머 정보 저장 시, ping과 sync api에서 addElapsedTime을 이용해 경과 시간을 더해주고 있었어요.
이를 로직의 간소화를 위해, 웹팀과 회의 후에 경과 시간이 아닌 현재 타이머의 시간을 요청받아 그대로 DB에 반영하도록 변경했어요.
https://github.com/morib-in/Morib-Server-v2/blob/8cbb35145dc19d44379cf59cccc9730c5e39c945/morib/src/main/java/org/morib/server/api/timerView/facade/TimerViewFacade.java#L68
=> Fix [#181] 타이머 정보 저장 시 Timer DB에 반영하는 방식 변경

morib/src/main/java/org/morib/server/api/allowGroupView/controller/AllowedGroupViewController.java, morib/src/main/java/org/morib/server/api/allowGroupView/facade/AllowedGroupViewFacade.java, morib/src/main/java/org/morib/server/domain/user/UserManager.java, morib/src/main/java/org/morib/server/domain/user/infra/User.java, morib/src/main/java/org/morib/server/global/common/Constants.java, morib/src/main/java/org/morib/server/global/oauth2/handler/OAuth2LoginSuccessHandler.java
- closes #176 
온보딩 건너뛰기 및 이탈 시 처리하는 로직을 추가했어요.
<br>
해당 api에 들어왔다는 건, 온보딩 완료 처리를 의미하므로 유저를 DB에서 찾은 후 온보딩 완료 처리를 해주었어요.
- interestArea의 default value를 `unknown`으로 처리하고, 쿼리 파라미터가 비어있어 `unknown`이면 건너뛰기로 인식하게 했어요.
- 추가적인 예외 상황을 대비해, Request Body에 required=false 옵션을 넣어 비어있는 경우 건너뛰기로 인식하게 했어요.
https://github.com/morib-in/Morib-Server-v2/blob/389db014657c84a431dd87edcaa479d3644b0448/morib/src/main/java/org/morib/server/api/allowGroupView/facade/AllowedGroupViewFacade.java#L190-L205
<br>
기존에 로그인 여부로 온보딩 여부를 식별했는데, 이를 User DB에 추가하여 식별하도록 변경했어요. 
로그인 성공 시, 해당 유저의 값을 전달하여 온보딩을 진행할지 말지 클라이언트에서 인식하도록 했어요.
https://github.com/morib-in/Morib-Server-v2/blob/389db014657c84a431dd87edcaa479d3644b0448/morib/src/main/java/org/morib/server/global/oauth2/handler/OAuth2LoginSuccessHandler.java#L53-L59
=> Refactor [#176] 온보딩 건너뛰기 및 예외 상황 처리

morib/src/main/java/org/morib/server/annotation/ValidUrl.java, morib/src/main/java/org/morib/server/api/allowGroupView/controller/AllowedGroupViewController.java, morib/src/main/java/org/morib/server/api/homeView/controller/HomeViewController.java, morib/src/main/java/org/morib/server/api/homeView/controller/TaskController.java, morib/src/main/java/org/morib/server/api/homeView/facade/HomeViewFacade.java, morib/src/main/java/org/morib/server/api/loginView/controller/UserAuthController.java, morib/src/main/java/org/morib/server/api/modalView/controller/CategoryController.java, morib/src/main/java/org/morib/server/api/modalView/controller/ModalViewController.java, morib/src/main/java/org/morib/server/api/modalView/controller/RelationshipController.java, morib/src/main/java/org/morib/server/api/settingView/controller/SettingViewController.java, morib/src/main/java/org/morib/server/api/timerView/controller/TimerViewController.java, morib/src/main/java/org/morib/server/domain/allowedSite/application/FetchSiteInfoServiceImpl.java, morib/src/main/java/org/morib/server/global/common/HealthCheckController.java, morib/src/main/java/org/morib/server/global/common/util/ApiResponseUtil.java, morib/src/main/java/org/morib/server/global/common/util/DataUtils.java, morib/src/main/java/org/morib/server/global/common/util/UrlUtils.java, morib/src/main/java/org/morib/server/global/common/util/UrlValidator.java, morib/src/main/java/org/morib/server/global/exception/GlobalExceptionHandler.java, morib/src/main/java/org/morib/server/global/jwt/CustomJwtAuthenticationEntryPoint.java, morib/src/main/java/org/morib/server/global/oauth2/handler/OAuth2LoginSuccessHandler.java
- closes #183
유효하지 않은 URL을 허용 서비스에 등록하고, 이를 조회할 때 도메인 이름을 파싱하게 되는데 해당 라이브러리에서 유효하지 않은 URL은 파싱할 수 없기 때문에 Exception이 발생했습니다. 
이에, 파싱이 불가한 URL의 경우 split을 통해 `www` 또는 프로토콜을 제외해 리턴하도록 변경했습니다. (개인 노션 계정이나 개발용 테스트 서버일 수도 있으므로)
https://github.com/morib-in/Morib-Server-v2/blob/f201a84cb31b3580a6ca34fee11afe8e338b977d/morib/src/main/java/org/morib/server/global/common/util/UrlUtils.java#L98-L131
<br>
추가로, URL 관련 코드가 허용 서비스 비즈니스 로직에 중복되어 포함되어 있는 것을 발견해 `UrlUtils` 유틸 클래스로 분리했습니다.
=> Fix [#183] 유효하지 않은 URL 허용서비스 조회 시 에러 핸들링

morib/src/main/java/org/morib/server/api/allowGroupView/facade/AllowedGroupViewFacade.java, morib/src/main/java/org/morib/server/api/modalView/controller/ModalViewController.java, morib/src/main/java/org/morib/server/api/modalView/dto/CreateCategoryRequestDto.java, morib/src/main/java/org/morib/server/api/timerView/controller/TimerViewController.java, morib/src/main/java/org/morib/server/api/timerView/dto/SaveTimerSessionRequestDto.java, morib/src/main/java/org/morib/server/api/timerView/facade/TimerViewFacade.java, morib/src/main/java/org/morib/server/global/common/util/DataUtils.java, morib/src/main/java/org/morib/server/global/config/SecurityConfig.java, morib/src/main/java/org/morib/server/global/jwt/JwtAuthenticationFilter.java
- closes #185 
3차 QA 사항인 입력값 유효성 검사 강화, 친구 목록 정렬 로직 추가, 친구 몰입 시간 표시 기준 변경, 
그리고 인증 필터의 예외 처리 로직 개선을 진행했어요.
*   `categoryName` 필드에 `@NotBlank` 어노테이션을 추가하여, 이름이 비어 있거나 공백만 있는 경우 요청이 실패하도록 수정했어요.
```java
public record CreateCategoryRequestDto(
@NotBlank
String categoryName
)
```
*   타이머 정보 저장 API 요청 시, 필수 필드(`taskId`, `timerStatus`, `targetDate`, `elapsedTime`)에 `@NotNull` 어노테이션 검증을 추가했어요.
```java
public record SaveTimerSessionRequestDto(
@NotNull
Long taskId,
@NotNull
int elapsedTime,
@NotNull
TimerStatus timerStatus,
@NotNull
LocalDate targetDate
)
```
*   타이머 하단 친구 목록 조회 로직에 `elapsedTime` 기준 내림차순 정렬 조건을 추가했어요.
*   우선순위가 온/오프라인 -> 오늘 몰입 시간 내림차순 -> 이름 오름차순 으로 표시되도록 변경했어요.
```java
public List<FetchRelationshipResponseDto> buildFetchRelationshipResponseDto(Long userId, List<Relationship> …
```
=> Fix [#185] 3차 QA 반영

morib/src/main/java/org/morib/server/annotation/IsToday.java, morib/src/main/java/org/morib/server/api/homeView/controller/HomeViewController.java, morib/src/main/java/org/morib/server/api/homeView/facade/HomeViewFacade.java, morib/src/main/java/org/morib/server/api/timerView/controller/TimerViewController.java, morib/src/main/java/org/morib/server/api/timerView/dto/TimerDtos.java, morib/src/main/java/org/morib/server/api/timerView/facade/TimerViewFacade.java, morib/src/main/java/org/morib/server/domain/timer/TimerManager.java, morib/src/main/java/org/morib/server/domain/timer/TimerSessionManager.java, morib/src/main/java/org/morib/server/domain/timer/application/FetchTimerService.java, morib/src/main/java/org/morib/server/domain/timer/application/FetchTimerServiceImpl.java, morib/src/main/java/org/morib/server/domain/timer/application/TimerSession/CalculateTimerSessionService.java, morib/src/main/java/org/morib/server/domain/timer/application/TimerSession/CalculateTimerSessionServiceImpl.java, morib/src/main/java/org/morib/server/domain/timer/application/TimerSession/CreateTimerSessionService.java, morib/src/main/java/org/morib/server/domain/timer/application/TimerSession/CreateTimerSessionServiceImpl.java, morib/src/main/java/org/morib/server/domain/timer/application/TimerSession/FetchTimerSessionService.java, morib/src/main/java/org/morib/server/domain/timer/application/TimerSession/FetchTimerSessionServiceImpl.java, morib/src/main/java/org/morib/server/domain/timer/infra/TimerSession.java, morib/src/main/java/org/morib/server/domain/timer/infra/TimerSessionRepository.java, morib/src/main/java/org/morib/server/domain/user/infra/User.java, morib/src/main/java/org/morib/server/global/common/util/IsTodayValidator.java, morib/src/main/java/org/morib/server/global/config/SecurityConfig.java, morib/src/main/java/org/morib/server/global/exception/GlobalExceptionHandler.java, morib/src/main/java/org/morib/server/global/jwt/JwtAuthenticationFilter.java, morib/src/main/java/org/morib/server/global/message/ErrorMessage.java, morib/src/main/java/org/morib/server/scheduler/TimerScheduler.java, morib/src/test/java/org/morib/server/facade/TimerFullScenarioIntegrationTest.java, morib/src/test/java/org/morib/server/facade/TimerMultiUserIntegrationTest.java
- closes #189 
타이머 기능을 전면 서버로 이관했어요. [관련 위키](https://github.com/morib-in/Morib-Server-v2/wiki/%ED%83%80%EC%9D%B4%EB%A8%B8-%EB%8F%99%EC%9E%91-%EB%B0%A9%EC%8B%9D-%EA%B0%9C%EC%84%A0)
- 할일 추가 후 타이머에 진입할 때 `TimerSession`이 없다면 생성하고, 가장 첫번째 할일이 자동으로 선택된 할일로 지정되도록 했어요. 
```java
Task firstTask = tasks.get(0);
Category findCategory = fetchCategoryService.fetchByUserIdAndTaskId(userId, firstTask.getId());
int elapsedTimeOfFirstTask = fetchTimerService.fetchElapsedTimeOrZeroByTaskAndTargetDate(firstTask, targetDate);
TimerSession findTimerSession = fetchTimerSessionService.fetchTimerSession(userId, targetDate);
if (findTimerSession == null) {
createTimerSessionService.create(userId, findCategory.getName(), firstTask, elapsedTimeOfFirstTask, TimerStatus.PAUSED, targetDate);
} else { …
```
=> Refactor [#189] 타이머 기능 전체 서버로 이관

morib/src/main/java/org/morib/server/api/allowGroupView/facade/AllowedGroupViewFacade.java, morib/src/main/java/org/morib/server/domain/allowedSite/application/FetchSiteInfoService.java, morib/src/main/java/org/morib/server/domain/allowedSite/application/FetchSiteInfoServiceImpl.java, morib/src/main/java/org/morib/server/global/common/util/UrlUtils.java, morib/src/main/java/org/morib/server/global/message/ErrorMessage.java
- closes #193 
계속해서 이슈가 발생했던 허용 서비스 관련 API의 URL 정규화 로직을 전면 수정했어요.
- 기획 요구사항에 따라 URL 정규화 로직을 수정했어요.
- 기획 요구사항 
> [유효성 검사]
•도메인 형식이 유효하지 않으면 (예: asdf, htp:/naver)
→ “유효한 도메인 형식이 아닙니다” 출력
•동일한 URL (host + pathname 기준)이 이미 등록된 경우
→ “이미 존재하는 서비스입니다” 출력
•입력값에 프로토콜이 없는 경우 자동으로 보정 (https:// 붙여서 파싱 시도)
•경로(/path)나 쿼리스트링(?query=123)은 있어도 됨, 비교를 위해 정규화 필요
[정규화]
1.프로토콜 제거
https://naver.com/page → [naver.com/page](http://naver.com/page)
http://naver.com/page → [naver.com/page](http://naver.com/page)
2.www. 제거
[www.naver.com/page](http://www.naver.com/page) → [naver.com/page](http://naver.com/page)
3.마지막 슬래시 / 제거
[naver.com/page/](http://naver.com/page/) → [naver.com/page](http://naver.com/page)
4.쿼리스트링 제거, pathname까지만 저장
[naver.com/page?foo=1&bar=2](http://naver.com/page?foo=1&bar=2) → …
=> Refactor [#193] URL 정규화 관련 로직 전면 수정

morib/src/main/java/org/morib/server/api/allowGroupView/facade/AllowedGroupViewFacade.java, morib/src/main/java/org/morib/server/global/common/util/UrlUtils.java
- closes #193 
- 원본 url을 그대로 메타 데이터를 추출하는 함수에 넣으니 프로토콜이 없는 경우 파비콘이 추출되지 않는 이슈가 있었어요.
- 이를 해결하기 위해 메타 데이터를 추출할 때 원본 URL을 일반적인 형식으로 보정하도록 `UrlUtils`에 유틸 함수를 추가했어요.
```java
public static String normalizeUrlForFavicon(String urlString) {
try {
// 프로토콜이 없으면 "https://" 추가
if (!urlString.matches("^(http://|https://).*")) {
urlString = "https://" + urlString;
}
URL url = new URL(urlString);
// 항상 https로 강제 (요구사항에 따라 변경 가능)
String scheme = "https";
// 호스트를 소문자로 변환하고 "www." 접두어 제거
String host = url.getHost().toLowerCase();
if (host.startsWith("www.")) {
host = host.substring(4);
}
// 포트: 기본 포트가 아니라면 포함 (예: https의 기본 포트 443)
int port = url.getPort();
String portPart = "";
if (port != -1 && port != 443) {
portPart = ":" + port;
}
// 경로: "/"인 경우나 빈 문자열은 빈 문자열로 처리하고, 나머지 경우 끝의 "/" 제거
String path = …
```
=> Fix [#193] 파비콘 추출을 위해 원본 URL 보정 후 파비콘 추출하도록 변경

morib/build.gradle, morib/src/main/java/org/morib/server/scheduler/S3LogUploader.java
- closes #207 
- Amazon S3를 이용한 자동 로그 적재 시스템을 구축했어요.
- AWS SDK v2를 사용했어요. `implementation 'io.awspring.cloud:spring-cloud-aws-starter-s3:3.1.1'`
- IAM 역할을 사용해, 액세스 키와 시크릿 키가 별도로 주입되지 않도록 했어요.
- 매일 새벽 5시에 스케줄링을 돌려서 docker volume에 마운트되어있던 전날의 로그들을 s3로 업로드하고, 로컬에 남아있는 로그 파일은 삭제하도록 구현했어요.
- 현재 상황에서는 이전의 로그 파일들이 로컬에 저장되어있어, 이를 s3에 업로드하는 코드로 작성했고 `2895132` 테스트 후 다시 코드를 원복할 예정이예요.
=> Feat [#207] S3를 이용한 로깅 시스템 구축 

morib/src/main/java/org/morib/server/scheduler/S3LogUploader.java
- closes #207 
테스트 용도의 코드를 삭제하고, 새벽 5시마다 이전 날짜의 로그 파일을 s3에 업로드하도록 수정했어요.
- 객체의 이름을 날짜와 yaml에서 주입한 log path를 이용해 생성하도록 했어요.
https://github.com/morib-in/Morib-Server-v2/blob/863121a363715a2c112829103f3eb250a2f7f201/morib/src/main/java/org/morib/server/scheduler/S3LogUploader.java#L71-L77
- s3에 업로드를 성공한 로그 파일을 로컬 머신에서 삭제하도록 했어요.
https://github.com/morib-in/Morib-Server-v2/blob/863121a363715a2c112829103f3eb250a2f7f201/morib/src/main/java/org/morib/server/scheduler/S3LogUploader.java#L79-L86
- 새벽 5시마다 스케줄링을 통해 로그 파일을 s3에 업로드하도록 했어요.
https://github.com/morib-in/Morib-Server-v2/blob/863121a363715a2c112829103f3eb250a2f7f201/morib/src/main/java/org/morib/server/scheduler/S3LogUploader.java#L33-L69
=> Refactor [#207] 새벽 5시에 이전 날짜의 로그 파일 업로드하도록 수정

morib/src/main/java/org/morib/server/api/allowGroupView/facade/AllowedGroupViewFacade.java, morib/src/main/java/org/morib/server/api/loginView/controller/UserAuthController.java, morib/src/main/java/org/morib/server/api/loginView/dto/UserReissueRequestDto.java, morib/src/main/java/org/morib/server/api/loginView/dto/UserReissueTmpRequestDto.java, morib/src/main/java/org/morib/server/api/timerView/controller/TimerViewController.java, morib/src/main/java/org/morib/server/api/timerView/facade/TimerViewFacade.java, morib/src/main/java/org/morib/server/global/common/util/UrlUtils.java, morib/src/main/java/org/morib/server/global/exception/GlobalExceptionHandler.java, morib/src/main/java/org/morib/server/global/exception/InvalidStateException.java, morib/src/main/java/org/morib/server/global/message/ErrorMessage.java
- closes #210 
최종 QA 사항들을 반영했어요.
- 클라이언트에서 일렉트론 도입으로 인한 요구사항에 따라, 토큰 재발급 api 요청 파라미터를 쿠키가 아닌 쿼리 파라미터 방식으로 임시 추가했어요.
https://github.com/morib-in/Morib-Server-v2/blob/0fb189389c648e6f929a472185692ac0ddc18b2d/morib/src/main/java/org/morib/server/api/loginView/controller/UserAuthController.java#L38-L43
- 상위 도메인 허용 시, 합치는 과정은 잘 진행되었지만 최종적으로 DB에 업데이트되는 레코드가 도메인이 그대로 메타 데이터 추출 파라미터로 들어가 제대로 파싱이 안되는 이슈가 있었어요.
- 요청 파라미터로 들어온 원본 Url의 상위 도메인 Full Url을 추출하는 유틸 함수를 추가했고, 해당 함수로 얻은 상위 도메인의 Full Url을 활용해 메타 데이터를 추출하도록 변경했어요.
https://github.com/morib-in/Morib-Server-v2/blob/0fb189389c648e6f929a472185692ac0ddc18b2d/morib/src/main/java/org/morib/server/api/allowGroupView/facade/AllowedGroupViewFacade.java#L249
https://github.com/morib-in/Morib-Server-v2/blob/0fb189389c648e6f929a472185692ac0ddc18b2d/morib/sr …
=> QA [#210] 최종 QA 반영

morib/src/main/java/org/morib/server/api/allowGroupView/facade/AllowedGroupViewFacade.java, morib/src/main/java/org/morib/server/domain/allowedSite/AllowedSiteManager.java
- closes #210 
상위 도메인 허용 API시, 합칠 URL이 1개인 경우 합쳐지지 않는 이슈가 있었어요. 2개 이상인 경우에만 합쳐질 수 있다고 잘못 생각했던 것이 문제였습니다.
- size가 2 이상이 아닌 비어있지 않은 경우 하도록 변경
```java
if (!findAllowedSites.isEmpty()) mergeToOne(UrlUtils.getTopDomainUrl(siteUrl), findAllowedSites);
``` 
- 상위 도메인 허용 api 파라미터에 전달된 siteUrl이 존재하지 않는 경우가 핸들링 되어있지 않아 추가했어요.
```java
if (fetchAllowedSiteService.fetchBySiteUrlAndAllowedGroupId(siteUrl, allowedGroupId) == null) throw new NotFoundException(ErrorMessage.NOT_FOUND);
```
- 상위 도메인 허용 시 최종적으로 생성되는 레코드의 siteUrl이 정규화되지 않고 DB에 추가되는 이슈가 있어, 최종적으로 merge 후 정규화해 DB 업데이트하도록 변경했어요.
```java
allowedSiteManager.updateAllowedSiteInfo(baseAllowedSite, fetchSiteInfoService.fetchSiteMetadataFromUrl(topDomainUrl), UrlUtils.normalizeUrl(topDomainUrl));
```
=> Fix [#210] 상위 도메인 허용 에러 해결

morib/src/main/java/org/morib/server/api/loginView/controller/UserAuthController.java, morib/src/main/java/org/morib/server/api/loginView/dto/WaitingUserWindowRequestDto.java, morib/src/main/java/org/morib/server/api/loginView/facade/UserAuthFacade.java, morib/src/main/java/org/morib/server/domain/user/application/service/CreateWaitingUserWindowService.java, morib/src/main/java/org/morib/server/domain/user/application/service/CreateWaitingUserWindowServiceImpl.java, morib/src/main/java/org/morib/server/domain/user/infra/WaitingUserWindow.java, morib/src/main/java/org/morib/server/domain/user/infra/WaitingUserWindowRepository.java, morib/src/main/java/org/morib/server/global/config/SecurityConfig.java
- closes #215 
- 랜딩 페이지에서 윈도우 사용자의 이메일을 수집하는 api를 추가했어요.
- 테이블 구성은 단순하게 `BaseTImeEntity`와 `id`, `email`로만 간결하게 구성했어요.
- `SecurityConfig`에 필터 검증 통과로 해당 api를 추가해 토큰 없이 서버에 들어오도록 했어요.
=> Feat [#215] 랜딩 페이지에서 윈도우 사용자 이메일 수집하는 api 추가 
